### ISSUE TITLE
MueLu:  Boundary Conditions Performance Loss

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#10459]
## Question
@trilinos/\<MueLu\>

Greeetings,

Lately I was trying to consolidate memory on an FEA system solve by implementing the boundary conditions as diagonal rows on my global matrix, rather than having 2 matrices for the original and reduced system. However, in doing so for some reason the MueLu preconditioner seems to give Belos a much harder time to converge, about 100 times more iterations to get the same answer as the previous method. Any idea what could be going on there? I attached the matrix in matrixmarket format and my MueLu parameters. Thanks for any help.

Adrian Diaz
[elasticity3D_share.txt](https://github.com/trilinos/Trilinos/files/8557035/elasticity3D_share.txt)
[A_matrix2.zip](https://github.com/trilinos/Trilinos/files/8557043/A_matrix2.zip)

**Comment by Adrian-Diaz** [comment]
[out_BC_removed.txt](https://github.com/trilinos/Trilinos/files/8557526/out_BC_removed.txt)
[out_BC_included.txt](https://github.com/trilinos/Trilinos/files/8557527/out_BC_included.txt)

**Comment by cgcgcg** [comment]
Can you bump up the number of eigenvalue iterations for both problems? I'd expect the resulting eigenvalue estimates to be identical, but they seem to differ.

**Comment by cgcgcg** [comment]
(Just double checking: did you check that the solution of the system with BCs eliminated solves the one with BCs included?)

**Comment by Adrian-Diaz** [comment]
Yea the solutions are almost identical, even the strain energy is virtually the same as printed at the end. This is the result for both with 500 max iterations for the eigenvalue estimate
[out_BC_included_500_eig.txt](https://github.com/trilinos/Trilinos/files/8557674/out_BC_included_500_eig.txt)
[out_BC_removed_500_eig.txt](https://github.com/trilinos/Trilinos/files/8557675/out_BC_removed_500_eig.txt)
.

**Comment by cgcgcg** [comment]
What I'm seeing is:
```
out_BC_included_500_eig.txt:"Ifpack2::Chebyshev": {Initialized: true, Computed: true, "Ifpack2::Details::Chebyshev":{degree: 2, lambdaMax: 2.86361, alpha: 7, lambdaMin: 0.409088, boost factor: 1.1}, Global matrix dimensions: [36663, 36663], Global nnz: 2603349}
out_BC_removed_500_eig.txt: "Ifpack2::Chebyshev": {Initialized: true, Computed: true, "Ifpack2::Details::Chebyshev":{degree: 2, lambdaMax: 3.08573, alpha: 7, lambdaMin: 0.440819, boost factor: 1.1}, Global matrix dimensions: [36300, 36300], Global nnz: 2577402}
```
So these matrices don't seem to have the same spectrum.

**Comment by cgcgcg** [comment]
Huh. I computed the spectral radius of D^-1 * A for the matrix you attached using scipy, and that gives me 3.08593796.

**Comment by cgcgcg** [comment]
What Trilinos SHA are you on?

**Comment by Adrian-Diaz** [comment]
Whats the SHA? The release version stated in the release notes this ran with is 12.2.

**Comment by cgcgcg** [comment]
What does `git rev-parse HEAD` in your Trilinos source say?

**Comment by Adrian-Diaz** [comment]
I get 5a67b70fb3816e1cea26554c650b4dc7ca26747d

**Comment by cgcgcg** [comment]
You could try to pass "chebyshev: max eigenvalue" = 3.08593796 in the "smoother: params". If that fixes things, we at least know that it's a problem with the spectral computations.

**Comment by Adrian-Diaz** [comment]
Doesn't seem to change the convergence speed.

**Comment by cgcgcg** [comment]
I ran your matrix on my end, with 500 iterations, and I get
```
chebyshev: max eigenvalue (calculated by Ifpack2) = 3.08579
"Ifpack2::Chebyshev": {Initialized: true, Computed: true, "Ifpack2::Details::Chebyshev":{degree: 2, lambdaMax: 3.08579, alpha: 7, lambdaMin: 0.440827, boost factor: 1.1}, Global matrix dimensions: [36663, 36663], Global nnz: 2603349}
```
This was with a Trilinos develop from ~ 3 weeks ago. So I guess this has been fixed in the meantime.

**Comment by Adrian-Diaz** [comment]
I'll try updating to see.

**Comment by Adrian-Diaz** [comment]
Is that from the Trilinos develop branch? I'm still getting the old value.

**Comment by cgcgcg** [comment]
Hm. Let's try something else. Can your run `./MueLu_Driver.exe --matrix=A_matrix2.txt` in `packages/muelu/test/scaling/`? You'll have to modify the input deck `scaling.xml` and set `repartition: enable = false`.

**Comment by Adrian-Diaz** [comment]
Its telling me there's a crash in the preconditioner setup if I run with those args. Its not printing the eigenvalue even with extreme verbosity.

**Comment by cgcgcg** [comment]
Ok. So at least we're seeing the same results in that case. Question is, what is different between running it from your driver and in our driver. You can also set "debug = True" in the "smoother: params". That will tell you in a lot of detail what the power iteration is doing. That way, you might be able to pin down how the two runs differ.

**Comment by Adrian-Diaz** [comment]
I couldn't see any difference in the DriverCore routines for PreconditionerSetup; other than the nullspace setting but that was being triggered anyway. Whatever is happening seems to be parametric if the eigenvalue estimate takes place there. Is it being done by this line?  A->SetMaxEigenvalueEstimate(-Teuchos::ScalarTraits<SC>::one());

**Comment by cgcgcg** [comment]
A matrix can cache an eigenvalue estimate. By setting that cached value to -1, we assure that a computation will be triggered once we get to the Chebyshev smoother construction.

**Comment by Adrian-Diaz** [comment]
Is the nullspace relevant to the eigenvalue estimate?

**Comment by cgcgcg** [comment]
No, it is not.

**Comment by Adrian-Diaz** [comment]
Copying over the scaling.xml params into the original elasticity3D.xml params didn't change it, also in that case Belos has growing error rather than shrinking 0_0.

**Comment by cgcgcg** [comment]
Could you try setting "debug = true" in the smoother list? That way we should be able to track down where the two eigenvalue estimates differ.

**Comment by Adrian-Diaz** [comment]
[Eig_Estimate_BC_included.txt](https://github.com/trilinos/Trilinos/files/8565720/Eig_Estimate_BC_included.txt)
[Eig_Estimate_BC_removed.txt](https://github.com/trilinos/Trilinos/files/8565721/Eig_Estimate_BC_removed.txt)

**Comment by cgcgcg** [comment]
When I run with the `MueLu_Driver` it does not print that. Could there be a difference between the matrix in the file and what you're running?

**Comment by cgcgcg** [comment]
If you're using the `Xpetra::IO` routines, you can try `writeLocal`. That one doesn't collect the matrix on a single rank and then prints, but outright writes the rank local matrices. That's one processing step less. Also, could you share how you enforce BCs?

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by Adrian-Diaz** [comment]
How do I invoke writeLocal, I couldn't find it in xpetra, will A->describe() be enough? The BCs are being added as trivial diagonal entries set equal to the condition on the DOF; I rescaled them by an arbitrary diagonal entry of the stiffness matrix to see if improving the condition number helped, which is why there aren't simply 1s there.

**Comment by cgcgcg** [comment]
https://github.com/trilinos/Trilinos/blob/7bc4eb697c4ccd9fab1742661da3260a1069d41a/packages/xpetra/sup/Utils/Xpetra_IO.hpp#L323

**Comment by Adrian-Diaz** [comment]
[A_matrixlocal.zip](https://github.com/trilinos/Trilinos/files/8567069/A_matrixlocal.zip)

I got the following 4 files.

**Comment by cgcgcg** [comment]
Hm, they look reasonable to me. I think you might have to hack something in here
https://github.com/trilinos/Trilinos/blob/97353f2ce580dcde02f4b04a78cccb5e1c942f43/packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp#L1131-L1133
to see where it thinks there are non-positive entries.

**Comment by cgcgcg** [comment]
One additional idea: these local matrices look like the rows aren't sorted. Are you telling Tpetra that they aren't sorted when you create the matrix? Maybe Tpetra thinks that the matrix is sorted, and takes some shortcuts in the diagonal extraction that aren't valid.

**Comment by Adrian-Diaz** [comment]
Not sure if its setting that, I built the matrix with a kokkos view constructor and a column map function from Tpetra Details:

Tpetra::Details::makeColMap<LO,GO,node_type>(colmap,dommap,DOF_Graph_Matrix.get_kokkos_view(), nullptr);

  size_t nnz = DOF_Graph_Matrix.size();
  
  //local indices in the graph using the constructed column map
  CArrayKokkos<LO, array_layout, device_type, memory_traits> stiffness_local_indices(nnz, "stiffness_local_indices");
  
  //row offsets with compatible template arguments
    row_pointers row_offsets = DOF_Graph_Matrix.start_index_;
    row_pointers row_offsets_pass("row_offsets", nlocal_nodes*num_dim+1);
    for(int ipass = 0; ipass < nlocal_nodes*num_dim + 1; ipass++){
      row_offsets_pass(ipass) = row_offsets(ipass);
    }

  size_t entrycount = 0;
  for(int irow = 0; irow < nlocal_nodes*num_dim; irow++){
    for(int istride = 0; istride < Stiffness_Matrix_Strides(irow); istride++){
      stiffness_local_indices(entrycount) = colmap->getLocalElement(DOF_Graph_Matrix(irow,istride));
      entrycount++;
    }
  }
  
  Global_Stiffness_Matrix = Teuchos::rcp(new MAT(local_dof_map, colmap, row_offsets_pass, stiffness_local_indices.get_kokkos_view(), Stiffness_Matrix.get_kokkos_view()));
  Global_Stiffness_Matrix->fillComplete();

**Comment by cgcgcg** [comment]
I guess that's this constructor:
https://github.com/trilinos/Trilinos/blob/7bc4eb697c4ccd9fab1742661da3260a1069d41a/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp#L776-L807

**Comment by Adrian-Diaz** [comment]
Hmm, that didn't seem to change the result. Not sure if the paramlist was passed correctly though:

  Teuchos::RCP<Teuchos::ParameterList> crs_matrix_params = Teuchos::rcp(new Teuchos::ParameterList("crsmatrix"));
  crs_matrix_params->set("sorted", false);
  Global_Stiffness_Matrix = Teuchos::rcp(new MAT(local_dof_map, colmap, row_offsets_pass, stiffness_local_indices.get_kokkos_view(), Stiffness_Matrix.get_kokkos_view(), crs_matrix_params));

**Comment by cgcgcg** [comment]
:-( 
Any luck with hacking something into the power method directly to check why it complains?

**Comment by Adrian-Diaz** [comment]
Well I ran on 1 rank and the result is the same. In that case its under the impression the diagonal entry (400,400) is 0 according to the error block. However I see 1.88034188034188046e+04 in the file output.

**Comment by cgcgcg** [comment]
Ok, next step: dump not only the matrix, but the diagonal vector. Maybe something is wrong with how that diagonal is computed?

**Comment by Adrian-Diaz** [comment]
What function should I use to print it? Also, the column map is the same as the row map for the 1 rank run, the default ordered set.

**Comment by Adrian-Diaz** [comment]
This is the diagonal made with the matrix getLocalDiagCopy routine
[Diagonal.txt](https://github.com/trilinos/Trilinos/files/8568828/Diagonal.txt)
.

**Comment by cgcgcg** [comment]
This getting more confusing. There are non-positive numbers in it, yet it claims there are? Which diag did you print, `D_rowmap` or `D_rangemap`? (It most likely doesn't matter, but you never know.)
https://github.com/trilinos/Trilinos/blob/97353f2ce580dcde02f4b04a78cccb5e1c942f43/packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp#L1113

**Comment by Adrian-Diaz** [comment]
It says it prints with the row map. I don't see an option for the range map.

**Comment by Adrian-Diaz** [comment]
The describe function for the matrix says the range map is the same as the row map; the domain map is the same as the column map. I tried printing the vectors ifpack2 is using with 
  D_rowMap->describe(*out_,Teuchos::VERB_EXTREME);
  D_rangeMap->describe(*out_,Teuchos::VERB_EXTREME);
but that causes a segfault.

**Comment by Adrian-Diaz** [comment]
Yea trying to print it is segfaulting. Valgrind didn't give me any hints without the prints. Maybe something to do with the diagonal offsets call?

**Comment by cgcgcg** [comment]
Maybe try printing the offsets to see if they are bad? (You might have to write the print loop yourself.)

**Comment by Adrian-Diaz** [comment]
I just blocked off that if check that tries using the diag offsets with a false so it defaults to the generic diagonal vector return I used and the eigenvalue and preconditioner setup works now, solution converges in 11 iterations again.

**Comment by cgcgcg** [comment]
Ok, so it's the offsets stuff that is bad. It does work in other cases though, so it would be good to know what goes wrong.

**Comment by Adrian-Diaz** [comment]
Turns out the segfaults for printing were just because I had debug set to false and they set out to null in that case. The casted matrix in the block looks fine, the output vector definitely has spurious zeros. now its a matter of figuring out why either the diag routine with offsets or the diag offsets are wrong.

**Comment by jhux2** [comment]
I am wondering if you are tickling a bug in the matrix constructor.  (Or as you suggest, the issue could be in the offset calculation.)  Most apps would not provide an explicit column map.  @csiefer2 @trilinos/tpetra?

**Comment by Adrian-Diaz** [comment]
The diag offsets don't seem like the right values after the first few rows. My only theory is this call to the graph function is somehow not working:
A_crsMat->getCrsGraph ()->getLocalDiagOffsets (diagOffsets_);

**Comment by cgcgcg** [comment]
My next suggestion would be to hack print statements in here
https://github.com/trilinos/Trilinos/blob/7bc4eb697c4ccd9fab1742661da3260a1069d41a/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L6823-L6824
to see what the values of `sorted` and `isFillComplete()` are.

**Comment by Adrian-Diaz** [comment]
Yea I think the issue is the parameter list setting for sorted = false didn't propagate down. Its still printing as true.

**Comment by Adrian-Diaz** [comment]
I'm a little shady on the sorted = false behavior since all I see is the constructor setting it to false if its set to false in the param list, then calling setAllIndices and I couldn't discern any sorting function being called before setting the flag to true suddenly.

**Comment by cgcgcg** [comment]
Ok, that seems like a bug to me.
Calling the `CrsGraph` constructor with a paramter list with "sorted = false"
https://github.com/trilinos/Trilinos/blob/7bc4eb697c4ccd9fab1742661da3260a1069d41a/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L664-L689
calls `setAllIndices`, but that then does this:
https://github.com/trilinos/Trilinos/blob/7bc4eb697c4ccd9fab1742661da3260a1069d41a/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L3197
so that now the matrix is tagged as sorted.

**Comment by cgcgcg** [comment]
@trilinos/tpetra Is it safe to move the processing of the parameter list in that constructor to after `setAllIndices`?

**Comment by Adrian-Diaz** [comment]
I tried that, it was highly ineffective.

**Comment by Adrian-Diaz** [comment]
Does it require sorting w.r.t the local indices or global index value of the entry? Also is it sorting for each row separately?

**Comment by cgcgcg** [comment]
It should sort each row separately wrt local indices.

**Comment by Adrian-Diaz** [comment]
Sorting with those utils seems to have worked.

**Comment by Adrian-Diaz** [comment]
Possibly unrelated, I've noticed when I go from serial to parallel the belos convergence tends to require around double the number of iterations; any idea why that might be?

**Comment by cgcgcg** [comment]
Are you seeing this independent of BCs? Can you post the logs of the setups for serial & parallel?

**Comment by Adrian-Diaz** [comment]
I tried again with the older version that removed them and it seemed more consistent, it'd only vary by a handful of iterations for the same test problem. I attached the logs for the first solve in the optimization process for the BC included case, in this case it's just about a 20% difference in iteration count though
[BC_included_1rank.txt](https://github.com/trilinos/Trilinos/files/8588938/BC_included_1rank.txt)
[BC_included_4rank.txt](https://github.com/trilinos/Trilinos/files/8588944/BC_included_4rank.txt)
.

**Comment by Adrian-Diaz** [comment]
For some reason setting it to 3 doesn't change the performance in my case; maybe because of how I set up the maps? I ran the logs for a restart case later in the optimization where the differences become more drastic. The matrix condition number is higher at this point.
[BC_included_1rank.txt](https://github.com/trilinos/Trilinos/files/8592135/BC_included_1rank.txt)
[BC_included_4rank.txt](https://github.com/trilinos/Trilinos/files/8592136/BC_included_4rank.txt)
.

**Comment by cgcgcg** [comment]
I don't see anything in the logs that would explain the difference. You could try out a different aggregation strategy, but no promise that this will work any better:
```
<Parameter name="aggregation: type" type="string" value="uncoupled"/>                                                                                                                                                                                                                                                               
<Parameter name="aggregation: drop scheme" type="string" value="distance laplacian"/>                                                                                                                                                                                                                                               
<Parameter name="aggregation: distance laplacian algo" type="string" value="scaled cut"/>                                                                                                                                                                                                                                           
<Parameter name="aggregation: drop tol" type="double" value="8.0"/>
```

**Comment by Adrian-Diaz** [comment]
Seems about the same, 110-120ish iterations.

**Comment by cgcgcg** [comment]
Hm, that's not great at all.

**Comment by Adrian-Diaz** [comment]
The more concerning thing is the iteration count increases linearly with MPI process count. What motivates the preconditioner to change? does the partitioning among processes effect the number of levels for example?

**Comment by cgcgcg** [comment]
Hm, that is indeed rather strange. The Chebyshev smoother should be independent of the number of ranks. The aggregates do depend a bit on distribution, but not to that extent. How is the problem initially distributed?

**Comment by Adrian-Diaz** [comment]
Do you mean the maps for the A matrix being fed in? or the preconditioner setup's distribution?

**Comment by cgcgcg** [comment]
The initial map. I could imagine terrible ways of distributing the data, but I don't think I saw that.

**Comment by Adrian-Diaz** [comment]
The row map is distributing contiguous chunks of the global size N as done by the map constructor for a global size. The BCs are being applied by zeroing out rows and columns on parts of the matrix that are always on rank 0 for the cases I've run; the graph and storage of nnz (even if the entry is just 0) is unchanged since I repopulate those parts again after the solve.

**Comment by cgcgcg** [comment]
Chunking the space of GIDs can be good or bad, it really depends on the ordering.

**Comment by Adrian-Diaz** [comment]
Its assigning the sequential chunks of GIDs to process ranks in order; for example 1-K goes to rank 0 K+1 - C to rank 1 and C+1 - N to rank 3.

**Comment by cgcgcg** [comment]
Yep, I get that. But you can come up with matrix orderings where that is absolutely terrible.

**Comment by Adrian-Diaz** [comment]
Is that in reference to the ordering of the rows or the columns?

**Comment by cgcgcg** [comment]
Lemme rephrase: you want as many entries of your matrix graph to be local to the MPI rank. The aggregation routine essentially ignores off-rank entries and only runs on the local portion. So if your mesh is distributed in a red-green ordering, you end up breaking this approach.

**Comment by Adrian-Diaz** [comment]
Ok, so if I understand this right the most consistent aggregation would occur if I did something like a spatial decomposition so that the ghost nodes are minimized to a halo; then the rows of the graph matrix see far less columns corresponding to ghost nodes. I guess an index reordering to minimize the bandwidth of the matrix would have a similar effect.

**Comment by cgcgcg** [comment]
That's correct. Most of the time, a distributed finite element code should already enforce something of that kind. But maybe something went wrong when setting up the system?

**Comment by Adrian-Diaz** [comment]
I see, well this mesh was imported from a rather simple mesh generation script, I really doubt it was optimizing the GIDs for any global properties. My own code isn't doing anything of the sort right now either. I could try with a mesh imported from ANSYS which seems to set up the GIDs to have far fewer ghosts for the cases I tried before. Otherwise I'll probably try to implement a spatial decomposition.

**Comment by Adrian-Diaz** [comment]
Decomposing the mesh with Zoltan2 seems to have made the iteration counts very consistent :-). Thanks for the help.

**Comment by cgcgcg** [comment]
Nice! Thank you for reporting back!
