### ISSUE TITLE
Tpetra:  unexercised test; missing ROCm test; change in sub package test behavior 

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#11002]
## Enhancement
@trilinos/tpetra

In our Trilinos builds, we double check certain properties of the build process, just to make sure that our building tool works as expected.  Among other properties, we track the number of Tpetra tests.  We noticed a few issues/questions:

- Following recent changes relevant to the switch to modern CMake, it seems the sub package behavior has changed.  It seems it is now no longer sufficient to set `Tpetra_ENABLE_TESTS` to `ON`.  In our builds, setting only this CMake variable to `ON` does no longer exercise the Core and TSQR tests.  It seems it is now necessary to set explicitly `TpetraCore_ENABLE_TESTS` and `TpetraTSQR_ENABLE_TESTS` to `ON` to exercise the Core and TSQR tests.

- PR #10552 deleted in `core/test/CrsMatrix/CrsMatrix_createDeepCopy.cpp` a number of preprocessor ifdef regions related to deprecated code.  However, this PR also deleted in `core/test/CrsMatrix/CMakeLists.txt` an IF region concerning this test.  Following this change, it appears the test is no longer exercised, but the file is still left in the source code.  It is unclear whether the source code file should be deleted or the test should be reintegrated in the `CMakeLists.txt `.

- The test related to `core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp` seems to follow an instantiation logic that is different from other Tpetra tests.  In the folder `core/test/CrsMatrix`, there are separate files that each exercise this test for a different exe space.  However, the ROCm case is missing.  It seems to be an important test, and it is unclear why the ROCm case is missing.  One way of solving this issue might perhaps be to use Tpetra ETI logic to instantiate the test for all relevant exe spaces.

**Comment by rppawlo** [comment]
@bartlettroscoe

**Comment by csiefer2** [comment]
Thanks for looking at this in detail!  When we're able to merge PRs again we'll take a look!

**Comment by maartenarnst** [comment]
Hi @bartlettroscoe.  Thank you for looking into this and for the links.  You will find in attachment the files that you asked for.  If you should have suggestions for how we could improve the cmake settings that we set, please do not hesitate.   

Small note: It seems GitHub doesn't allow .json files to be uploaded, so I'm adding .txt to the CMakePresets.json filename.  

[CMakePresets.json.txt](https://github.com/trilinos/Trilinos/files/9540159/CMakePresets.json.txt)
[stdout.txt](https://github.com/trilinos/Trilinos/files/9540162/stdout.txt)
[stderr.txt](https://github.com/trilinos/Trilinos/files/9540163/stderr.txt)
[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/9540164/CMakeCache.txt)

**Comment by bartlettroscoe** [comment]
@maartenarnst, thanks for the info.  The important bits of the output shown the those files are:

```
Preset CMake variables:

  ...
  Tpetra_ENABLE_EXAMPLES="OFF"
  Tpetra_ENABLE_TESTS="ON"
  ...
  Trilinos_ENABLE_EXAMPLES="ON"
  ...

...

Explicitly enabled packages on input (by user):  ... Tpetra ... 12

...

Enabling subpackages for hard enables of parent packages due to Trilinos_ENABLE_<PARENT_PACKAGE>=ON ...

...
-- Setting subpackage enable Trilinos_ENABLE_TpetraTSQR=ON because parent package Trilinos_ENABLE_Tpetra=ON
-- Setting subpackage enable Trilinos_ENABLE_TpetraCore=ON because parent package Trilinos_ENABLE_Tpetra=ON
...

Disabling subpackage tests/examples based on parent package tests/examples disables ...

-- Setting TpetraTSQR_ENABLE_EXAMPLES=OFF because parent package Tpetra_ENABLE_EXAMPLES=OFF
-- Setting TpetraCore_ENABLE_EXAMPLES=OFF because parent package Tpetra_ENABLE_EXAMPLES=OFF

Enabling all tests and/or examples that have not been explicitly disabled because Trilinos_ENABLE_[TESTS,EXAMPLES]=ON ...

...
-- Setting TpetraTSQR_ENABLE_TESTS=OFF
-- Setting TpetraCore_ENABLE_TESTS=OFF
...
```

This definingly looks like a defect (and a missing test case in TriBITS).  I will take a closer look.

**Comment by maartenarnst** [comment]
@bartlettroscoe, thanks!

**Comment by bartlettroscoe** [comment]
FYI: With the merge of PR #11099, the subpackage test enable behavior bug described [above](https://github.com/trilinos/Trilinos/issues/11002#issuecomment-1244293784) should be fixed.

**Comment by csiefer2** [comment]
@maartenarnst How much of this issue still needs to be fixed?

**Comment by maartenarnst** [comment]
Hi @bartlettroscoe and @csiefer2.  Thanks for following up on this issue. And thanks for the fix in TriBits!

There were three items in this issue.  

The item of the subpackage test enable behavior was solved in Roscoe's PR.  I also confirmed in our build that the fix works!

The other two items are still open:
- the file `core/test/CrsMatrix/CrsMatrix_createDeepCopy.cpp` is not used: I am unsure what to do; the Tpetra team is probably best placed to decide whether this file can be deleted.
- the test related to `core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp` is missing the ROCm case: this can easily be solved by adding a new file `Tpetra_Test_CrsMatrix_WithGraph_HIP.cpp` along the lines of the existing file `Tpetra_Test_CrsMatrix_WithGraph_Cuda.cpp` and then adding the new file in the `CMakeLists.txt`.  I have made such a modification in our build, compiled with ROCm 5.2, and confirmed that all goes well.  I submit this as a PR to close this?
