### ISSUE TITLE
Intrepid2: compiler warning

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11058]
```
In member function 'void Intrepid2::FunctorCellTools::F_getSubcvCoords_Polygon2D<subcvCoordViewType, cellCoordViewType, mapViewType>::operator()(Intrepid2::ordinal_type) const [with subcvCoordViewType = Kokkos::DynRankView<double, Kokkos::Serial>; cellCoordViewType = const Kokkos::DynRankView<double, Kokkos::LayoutStride, Kokkos::Serial>; mapViewType = Kokkos::View<int**, Kokkos::Serial>]':
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)' writing 24 bytes into a region of size 16 overflows the destination [-Wstringop-overflow=]
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)' writing 24 bytes into a region of size 16 overflows the destination [-Wstringop-overflow=]
```

FYI

**Comment by cgcgcg** [comment]
@trilinos/intrepid2

**Comment by VictorEijkhout** [comment]
```
/admin/build/admin/rpms/stampede2/BUILD/trilinos-13.4.0/packages/kokkos/core/src/Kokkos_Parallel_Reduce.hpp:1865:76: warning: 'static std::enable_if_t<(Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::is_array_reduction && std::is_pointer<_Ptr>::value)> Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(const string&, const PolicyType&, const FunctorType&, ReturnType&) [with Dummy = double*; PolicyType = Kokkos::TeamPolicy<Kokkos::Serial>; FunctorType = Zoltan2::ReduceWeightsFunctor<Kokkos::TeamPolicy<Kokkos::Serial>, double, int, int, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, double>; ReturnType = double*; std::enable_if_t<(Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::is_array_reduction && std::is_pointer<_Ptr>::value)> = void; std::string = std::__cxx11::basic_string<char>]' is deprecated: Array reductions with a raw pointer return type a deprecated. Use a Kokkos::View as return argument! [-Wdeprecated-declarations]
 1865 |   Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
 1866 |       "", policy, functor, return_value_impl);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/admin/build/admin/rpms/stampede2/BUILD/trilinos-13.4.0/packages/kokkos/core/src/Kokkos_Parallel_Reduce.hpp:1625:72: note: declared here
 1625 |       enable_if_t<is_array_reduction && std::is_pointer<Dummy>::value> execute(
      |                                                                        ^~~~~~~
```

**Comment by cgcgcg** [comment]
I think the array reduction one might get fixed by #11047, but there isn't enough context for the error message to be sure.

**Comment by rppawlo** [comment]
@mperego

**Comment by mperego** [comment]
@VictorEijkhout is the warning still happening after the merge of #11047? If so, can you give us some details about the build (version, compiler etc.) so that we can reproduce it?

**Comment by VictorEijkhout** [comment]
Pull the repo, default branch?

**Comment by cgcgcg** [comment]
develop branch. #11047 hasn't made it to master yet.

**Comment by mperego** [comment]
@VictorEijkhout PR #11047 did indeed fix some warnings. However, I was not able to reproduce the warnings you see. If you are willing to provide more info on your build (the compiler you are using, at least) I can look further into it.

**Comment by VictorEijkhout** [comment]
develop branch gives a new Intrepid warning, but it looks like something that needs to be adressed:

```
In member function 'void Intrepid2::FunctorCellTools::F_getSubcvCoords_Polygon2D<subcvCoordViewType, cellCoordViewType, mapViewType>::operator()(Intrepid2::ordinal_type) const [with subcvCoordViewType = Kokkos::DynRankView<double, Kokkos::Serial>; cellCoordViewType = const Kokkos::DynRankView<double, Kokkos::LayoutStride, Kokkos::Serial>; mapViewType = Kokkos::View<int**, Kokkos::Serial>]':
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)' forming offset [17, 24] is out of the bounds [0, 16] of object 'buf_center' with type 'value_type [2]' {aka 'double [2]'} [-Warray-bounds]
In file included from /admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Cell/Intrepid2_CellTools.hpp:1619,
                 from /admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Discretization/FunctionSpaceTools/Intrepid2_FunctionSpaceTools.hpp:64,
                 from /admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp:49:
/admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefControlVolume.hpp:161:20: note: 'buf_center' declared here
  161 |         value_type buf_center[2], buf_midpts[4*2];
      |                    ^~~~~~~~~~
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)' forming offset [17, 24] is out of the bounds [0, 16] of object 'buf_center' with type 'value_type [2]' {aka 'double [2]'} [-Warray-bounds]
/admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefControlVolume.hpp:161:20: note: 'buf_center' declared here
```

I'm running with gcc 9.1 (sorry, 5 year old system, no one feels called upon to roll out support for newer compilers)

**Comment by VictorEijkhout** [comment]
But the original warning still seems to be there:

```
In member function 'void Intrepid2::FunctorCellTools::F_getSubcvCoords_Polygon2D<subcvCoordViewType, cellCoordViewType, mapViewType>::operator()(Intrepid2::ordinal_type) const [with subcvCoordViewType = Kokkos::DynRankView<double, Kokkos::Serial>; cellCoordViewType = const Kokkos::DynRankView<double, Kokkos::LayoutStride, Kokkos::Serial>; mapViewType = Kokkos::View<int**, Kokkos::Serial>]':
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)' forming offset [17, 24] is out of the bounds [0, 16] of object 'buf_center' with type 'value_type [2]' {aka 'double [2]'} [-Warray-bounds]
In file included from /admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Cell/Intrepid2_CellTools.hpp:1619,
                 from /admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Discretization/FunctionSpaceTools/Intrepid2_FunctionSpaceTools.hpp:64,
                 from /admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp:49:
/admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefControlVolume.hpp:161:20: note: 'buf_center' declared here
  161 |         value_type buf_center[2], buf_midpts[4*2];
      |                    ^~~~~~~~~~
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)' forming offset [17, 24] is out of the bounds [0, 16] of object 'buf_center' with type 'value_type [2]' {aka 'double [2]'} [-Warray-bounds]
/admin/build/admin/rpms/stampede2/BUILD/trilinos-git20220928/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefControlVolume.hpp:161:20: note: 'buf_center' declared here
```

**Comment by mperego** [comment]
I looked into that a bit more. I think the issue is that we allocate arrays for two-dimensional points:
`value_type buf_center[2], buf_midpts[4*2];`
https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefControlVolume.hpp#L161
which is correct for this 2D function, but then we call getBarycenter() that has a case for 3d coordinates:
https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefControlVolume.hpp#L95

So the code is fine but it triggers a compiler warning. I guess we could avoid this by simply allocating larger arrays at line 161, that is:
`value_type buf_center[3], buf_midpts[4*3];`

@CamelliaDPG should we do this? I guess the alternative is to have specialized getBarycenter functions for 2D and 3D.

**Comment by CamelliaDPG** [comment]
@mperego, given that the 2D and 3D cases are completely separate algorithms in getBarycenter, I think it makes sense to split them apart.  I'd prefer not to allocate a larger array just to avoid a compiler warning.  But I think implementing getBarycenter2D() and getBarycenter3D() is actually better semantically than what we have right now: in the 1D case or d > 3 case, getBaryCenter() silently does nothing.  And we can correct the capitalization while we're at it!  (Barycenter, not BaryCenter.)

**Comment by mperego** [comment]
Sounds good. I'll do that. I noticed that `getBaryCenter` is only used in the `F_getSubcvCoord_XXX` functions, so it might be better to avoid introducing extra functions and add the needed few extra lines of code to compute the barycenter directly into the `F_getSubcvCoord_XXX` functions.
In fact we already have a barycenter function for reference shapes. And this `getBaryCenter` barycenter function on physical shape is only correct for affine meshes.

**Comment by mperego** [comment]
PR #11086 should have fixed these warnings. Closing the issue. Feel free to reopen it if you still observe these warnings.
