### ISSUE TITLE
/MueLu_BlockedDirectSolver.cpp.o fails to compile under gcc

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1128]
here is a compile line.  Not sure why this is happening.. 

/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp: In instantiation of ‘Teuchos::RCP<MueLu::SmootherPrototype<Scalar, LocalOrdinal, GlobalOrdinal, Node> > MueLu::BlockedDirectSolver<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Copy() const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>]’:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:3:   required from here
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp:181:17: error: invalid new-expression of abstract class type ‘MueLu::BlockedDirectSolver<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’
     return rcp (new BlockedDirectSolver (*this));
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from packages/muelu/src/MueLu_BlockedDirectSolver.hpp:1:0,
                 from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp:65,
                 from packages/muelu/src/Utils/ExplicitInstantiation/MueLu_BlockedDirectSolver.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_decl.hpp:85:9: note:   because the following virtual functions are pure within ‘MueLu::BlockedDirectSolver<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’:
   class BlockedDirectSolver : public SmootherPrototype<Scalar,LocalOrdinal,GlobalOrdinal,Node>
         ^~~~~~~~~~~~~~~~~~~
In file included from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherPrototype_decl.hpp:51:0,
                 from packages/muelu/src/MueLu_SmootherPrototype.hpp:1,
                 from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_decl.hpp:63,
                 from packages/muelu/src/MueLu_BlockedDirectSolver.hpp:1,
                 from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp:65,
                 from packages/muelu/src/Utils/ExplicitInstantiation/MueLu_BlockedDirectSolver.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherBase.hpp:94:20: note: 	size_t MueLu::SmootherBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::getNodeSmootherComplexity() const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; size_t = long unsigned int]
     virtual size_t getNodeSmootherComplexity() const= 0;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from packages/muelu/src/Utils/ExplicitInstantiation/MueLu_BlockedDirectSolver.cpp:55:0:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp: In instantiation of ‘Teuchos::RCP<MueLu::SmootherPrototype<Scalar, LocalOrdinal, GlobalOrdinal, Node> > MueLu::BlockedDirectSolver<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Copy() const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = long int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>]’:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:3:   required from here
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp:181:17: error: invalid new-expression of abstract class type ‘MueLu::BlockedDirectSolver<double, int, long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’
     return rcp (new BlockedDirectSolver (*this));
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from packages/muelu/src/MueLu_BlockedDirectSolver.hpp:1:0,
                 from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp:65,
                 from packages/muelu/src/Utils/ExplicitInstantiation/MueLu_BlockedDirectSolver.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_decl.hpp:85:9: note:   because the following virtual functions are pure within ‘MueLu::BlockedDirectSolver<double, int, long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’:
   class BlockedDirectSolver : public SmootherPrototype<Scalar,LocalOrdinal,GlobalOrdinal,Node>
         ^~~~~~~~~~~~~~~~~~~
In file included from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherPrototype_decl.hpp:51:0,
                 from packages/muelu/src/MueLu_SmootherPrototype.hpp:1,
                 from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_decl.hpp:63,
                 from packages/muelu/src/MueLu_BlockedDirectSolver.hpp:1,
                 from /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp:65,
                 from packages/muelu/src/Utils/ExplicitInstantiation/MueLu_BlockedDirectSolver.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherBase.hpp:94:20: note: 	size_t MueLu::SmootherBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::getNodeSmootherComplexity() const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = long int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; size_t = long unsigned int]
     virtual size_t getNodeSmootherComplexity() const= 0;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bathmatt** [comment]
dir-drekar (gcc) 9 $ grep -i mue configure.sh
EXPERIMENTAL_MUELU=ON

-D Trilinos_ENABLE_MueLu:BOOL=${EXPERIMENTAL_MUELU}  \
-D MueLu_ENABLE_Experimental:BOOL=${EXPERIMENTAL_MUELU} \
-D Xpetra_ENABLE_Experimental:BOOL=${EXPERIMENTAL_MUELU} \
-D MueLu_ENABLE_Amesos2:BOOL=ON \
dir-drekar (gcc) 10 $ grep -i teko configure.sh
-D Trilinos_ENABLE_Teko:BOOL=ON \
dir-drekar (gcc) 11 $ grep -i amesos configure.sh
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
-D MueLu_ENABLE_Amesos2:BOOL=ON \
dir-drekar (gcc) 12 $

**Comment by bathmatt** [comment]
@csiefer2 it looks like it was one of your pushes that broke the code.  83cc5d055d9c530dc37c12d339885e7a215ac54b still works.

**Comment by csiefer2** [comment]
@bathmatt Fix pushed.  Please confirm it works and close.

**Comment by bathmatt** [comment]
Not fixed.


from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_def.hpp:52,
                 from
packages/muelu/src/Utils/ExplicitInstantiation/MueLu_TekoSmoother.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:
In instantiation of ‘Teuchos::RCP<MueLu::SmootherPrototype<double, int,
GlobalOrdinal, Node> > MueLu::TekoSmoother<double, int, GlobalOrdinal,
Node>::Copy() const [with GlobalOrdinal = int; Node =
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>]’:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:3:
required from here
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:328:55:
error: invalid new-expression of abstract class type
‘MueLu::TekoSmoother<double, int, int,
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’
     RCP<SmootherPrototype> Copy() const { return rcp (new TekoSmoother
(*this)); }

^~~~~~~~~~~~~~~~~~~~~~~~
In file included from packages/muelu/src/MueLu_TekoSmoother.hpp:1:0,
                 from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_def.hpp:52,
                 from
packages/muelu/src/Utils/ExplicitInstantiation/MueLu_TekoSmoother.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:190:9:
note:   because the following virtual functions are pure within
‘MueLu::TekoSmoother<double, int, int,
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’:
   class TekoSmoother<double,int,GlobalOrdinal,Node> : public
SmootherPrototype<double,int,GlobalOrdinal,Node>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherPrototype_decl.hpp:51:0,
                 from packages/muelu/src/MueLu_SmootherPrototype.hpp:1,
                 from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:65,
                 from packages/muelu/src/MueLu_TekoSmoother.hpp:1,
                 from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_def.hpp:52,
                 from
packages/muelu/src/Utils/ExplicitInstantiation/MueLu_TekoSmoother.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherBase.hpp:94:20:
note:     size_t MueLu::SmootherBase<Scalar, LocalOrdinal, GlobalOrdinal,
Node>::getNodeSmootherComplexity() const [with Scalar = double;
LocalOrdinal = int; GlobalOrdinal = int; Node =
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; size_t = long
unsigned int]
     virtual size_t getNodeSmootherComplexity() const= 0;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from packages/muelu/src/MueLu_TekoSmoother.hpp:1:0,
                 from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_def.hpp:52,
                 from
packages/muelu/src/Utils/ExplicitInstantiation/MueLu_TekoSmoother.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:
In instantiation of ‘Teuchos::RCP<MueLu::SmootherPrototype<double, int,
GlobalOrdinal, Node> > MueLu::TekoSmoother<double, int, GlobalOrdinal,
Node>::Copy() const [with GlobalOrdinal = long int; Node =
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>]’:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:3:
required from here
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:328:55:
error: invalid new-expression of abstract class type
‘MueLu::TekoSmoother<double, int, long int,
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’
     RCP<SmootherPrototype> Copy() const { return rcp (new TekoSmoother
(*this)); }

^~~~~~~~~~~~~~~~~~~~~~~~
In file included from packages/muelu/src/MueLu_TekoSmoother.hpp:1:0,
                 from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_def.hpp:52,
                 from
packages/muelu/src/Utils/ExplicitInstantiation/MueLu_TekoSmoother.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:190:9:
note:   because the following virtual functions are pure within
‘MueLu::TekoSmoother<double, int, long int,
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’:
   class TekoSmoother<double,int,GlobalOrdinal,Node> : public
SmootherPrototype<double,int,GlobalOrdinal,Node>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherPrototype_decl.hpp:51:0,
                 from packages/muelu/src/MueLu_SmootherPrototype.hpp:1,
                 from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp:65,
                 from packages/muelu/src/MueLu_TekoSmoother.hpp:1,
                 from
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_def.hpp:52,
                 from
packages/muelu/src/Utils/ExplicitInstantiation/MueLu_TekoSmoother.cpp:55:
/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherBase.hpp:94:20:
note:     size_t MueLu::SmootherBase<Scalar, LocalOrdinal, GlobalOrdinal,
Node>::getNodeSmootherComplexity() const [with Scalar = double;
LocalOrdinal = int; GlobalOrdinal = long int; Node =
Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; size_t = long
unsigned int]
     virtual size_t getNodeSmootherComplexity() const= 0;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jhux2** [comment]
@csiefer2 Would you like me to take a look at this?
@bathmatt Which gcc are you using?  Besides these, what other cmake options do we need to enable?

```
-D Trilinos_ENABLE_MueLu:BOOL=${EXPERIMENTAL_MUELU}
-D MueLu_ENABLE_Experimental:BOOL=${EXPERIMENTAL_MUELU}
-D Xpetra_ENABLE_Experimental:BOOL=${EXPERIMENTAL_MUELU}
-D MueLu_ENABLE_Amesos2:BOOL=ON
-D Trilinos_ENABLE_Teko:BOOL=ON
-D Trilinos_ENABLE_Amesos:BOOL=ON
-D Trilinos_ENABLE_Amesos2:BOOL=ON
-D MueLu_ENABLE_Amesos2:BOOL=ON
```

**Comment by csiefer2** [comment]
@jhux2 Take a crack, if you'd like.  It built for me, so it might be my environment...

**Comment by bathmatt** [comment]
https://github.com/trilinos/Trilinos/issues/1113 has my configure,

Also, this is failing in the nightly it looks like.

**Comment by jhux2** [comment]
@bathmatt Just want to be sure -- this issue is unrelated to CUDA, correct?

**Comment by jhux2** [comment]
@bathmatt What I mean is, have you seen this problem occur without CUDA?

**Comment by jhux2** [comment]
Ok, I see this is happening w/o CUDA from the dashboard.

**Comment by jhux2** [comment]
I was able to fix those errors, now working on the following:

```
../../../src/libmuelu.so.12.11: undefined reference to `vtable for MueLu::Amesos2Smoother<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >'
../../../src/Interface/libmuelu-interface.so.12.11: undefined reference to `MueLu::TekoSmoother<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::getNodeSmootherComplexity() const'
../../../src/libmuelu.so.12.11: undefined reference to `VTT for MueLu::Ifpack2Smoother<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >'
../../../src/libmuelu.so.12.11: undefined reference to `vtable for MueLu::Ifpack2Smoother<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >'
../../../src/libmuelu.so.12.11: undefined reference to `VTT for MueLu::Amesos2Smoother<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >'
../../../src/Interface/libmuelu-interface.so.12.11: undefined reference to `MueLu::TekoSmoother<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::getNodeSmootherComplexity() const'
```

**Comment by jhux2** [comment]
@bathmatt I just sent you a patch.  Please try it out and let me know if it fixes the MueLu errors you're seeing.

**Comment by jhux2** [comment]
@bathmatt Patch has been pushed in commit 5bf06c13f.

**Comment by tawiesn** [comment]
Is this fixed?

**Comment by jhux2** [comment]
Closing, please reopen if necessary.
