### ISSUE TITLE
trilinos.org: insecure connectivity

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#120]
trilinos.org is served only with HTTPS (which is good), but all kinds of things are misconfigured. For one, the server only supports TLS 1.0.

![mess](https://cloud.githubusercontent.com/assets/181628/12703640/5ba480c8-c848-11e5-84d9-04ec542e69f4.png)

Check out https://www.ssllabs.com/ssltest/analyze.html?d=trilinos.org for more details.

**Comment by jwillenbring** [comment]
The TLS 1.0 issue was resolved. The admin indicated no other high-priority issues are mentioned and was satisfied to close the ticket.

**Comment by nschloe** [comment]
There are still other issues that has browsers complain. For one, the server still supports RC4 and the [deprecated](https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know) SHA1. As Google Chrome puts it:

> This page is insecure (broken HTTPS).
The certificate for this site expires in 2017 or later, and the certificate chain contains a certificate signed using SHA-1.

**Comment by psanan** [comment]
FWIW, Firefox (52.0.1, OS X 10.12) also considers the connection insecure.
![screen shot 2017-03-20 at 12 49 48](https://cloud.githubusercontent.com/assets/8024239/24098650/e57eba20-0d6b-11e7-9557-7e29bfc33470.png)

**Comment by jwillenbring** [comment]
I am in the process of resolving this.

**Comment by jwillenbring** [comment]
This should be resolved as of late last week. I tested it on chrome and Firefox where I previously was met with the security error. We had to update the certificate.

**Comment by nschloe** [comment]
Not sure what was tested here, but the issue still exists for me:

![t1](https://cloud.githubusercontent.com/assets/181628/24792527/a88b4d92-1b7e-11e7-9037-06d34117e0e8.png)

This is a screenshot from Chrome; I get the same behavior on Firefox.

**Comment by nschloe** [comment]
@jwillenbring Would you like to reopen this one?

**Comment by nschloe** [comment]
@jwillenbring Tested with the latest Chrome 58, still broken.

**Comment by ndsist** [comment]
Not sure it's strictly related with this issue, but when I run

`wget -nv "https://trilinos.org/oldsite/download/files/trilinos-11.12.1-Source.tar.bz2"`

I get

`ERROR: cannot verify trilinos.org's certificate, issued by ‘CN=USERTrust RSA Domain Validation Secure Server CA,O=The USERTRUST Network,L=Jersey City,ST=New Jersey,C=US’:
  Unable to locally verify the issuer's authority.
To connect to trilinos.org insecurely, use '--no-check-certificate'.`
