### ISSUE TITLE
Ifpack2 FastILU: Valgrind warnings

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#12379]
@trilinos/ifpack2 @jgfouca 

## Bug Report
Since some of the FastILU CMake logic was fixed (#12338) it is also run through our valgrind testing. It seems that there are a couple of warnings: https://testing.sandia.gov/cdash/viewDynamicAnalysis.php?buildid=11629407

**Comment by jgfouca** [comment]
@cgcgcg . Thanks, I will investigate.

**Comment by cgcgcg** [comment]
@jgfouca Thanks! There are some warnings that are not related to your changes in MDF that should get fixed by the next Kokkkos Kernels promotion.

**Comment by jgfouca** [comment]
@cgcgcg , sorry it took me a while to get around to this. I'm trying to see how many of these valgrind issues still need to be reolved. When I click the red box under "Defect Count", I get a blank page. What's the best way to view the current valgrind issues? Also, what's the best way to reproduce the issues on my workstation?

**Comment by cgcgcg** [comment]
@jgfouca Seems that the CDash is broken. However, I was able to extract some of the output from the nightly test run directly.

```
valgrind --max-stackframe=3835488 --trace-children=yes --leak-check=full --gen-suppressions=all --error-limit=no --suppressions=cmake/ctest/drivers/geminga/valgrind_suppressions.txt packages/ifpack2/test/unit_tests/Ifpack2_AdditiveSchwarz.exe
```
gives
```
==2741== Memcheck, a memory error detector
==2741== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2741== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==2741== Command: /home/jhu/code/trilinos-test/SERIAL-DEBUG_VALGRIND/BUILD/packages/ifpack2/test/unit_tests/Ifpack2_AdditiveSchwarz.exe
==2741== Parent PID: 11790
==2741== 
==2741== 
==2741== HEAP SUMMARY:
==2741==     in use at exit: 192 bytes in 5 blocks
==2741==   total heap usage: 113,336 allocs, 113,331 frees, 15,196,039 bytes allocated
==2741== 
==2741== 4 bytes in 1 blocks are definitely lost in loss record 1 of 5
==2741==    at 0x4C2AC38: operator new[](unsigned long) (vg_replace_malloc.c:433)
==2741==    by 0x60F9782: FastICPrec&lt;int, double, Kokkos::Serial&gt;::symbolicILU() (shylu_fastic.hpp:322)
==2741==    by 0x60F8245: FastICPrec&lt;int, double, Kokkos::Serial&gt;::initialize() (shylu_fastic.hpp:214)
==2741==    by 0x60F6B54: Ifpack2::Details::Fic&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::initLocalPrec() (Ifpack2_Details_Fic_def.hpp:99)
==2741==    by 0x5F8B251: Ifpack2::Details::FastILU_Base&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::initialize() (Ifpack2_Details_FastILU_Base_def.hpp:277)
==2741==    by 0x5E941CE: Ifpack2::Details::LinearSolver&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::symbolic() (Ifpack2_Details_LinearSolver_def.hpp:171)
==2741==    by 0x5ADBA8D: Ifpack2::AdditiveSchwarz&lt;Tpetra::RowMatrix&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;, Ifpack2::Preconditioner&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt; &gt;::initialize() (Ifpack2_AdditiveSchwarz_def.hpp:1072)
==2741==    by 0x4A9CB4: (anonymous namespace)::Ifpack2AdditiveSchwarz_FastIC_UnitTest&lt;double, int, long long&gt;::runUnitTestImpl(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;, bool&amp;) const (Ifpack2_UnitTestAdditiveSchwarz.cpp:1405)
==2741==    by 0x1633DA13: Teuchos::UnitTestBase::runUnitTest(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) const (Teuchos_UnitTestBase.cpp:62)
==2741==    by 0x1634318E: Teuchos::UnitTestRepository::runUnitTestImpl(Teuchos::UnitTestBase const&amp;, Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) (Teuchos_UnitTestRepository.cpp:539)
==2741==    by 0x163419F5: Teuchos::UnitTestRepository::runUnitTests(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) (Teuchos_UnitTestRepository.cpp:317)
==2741==    by 0x16342B16: Teuchos::UnitTestRepository::runUnitTestsFromMain(int, char**) (Teuchos_UnitTestRepository.cpp:423)
==2741== 
==2741== 4 bytes in 1 blocks are definitely lost in loss record 2 of 5
==2741==    at 0x4C2AC38: operator new[](unsigned long) (vg_replace_malloc.c:433)
==2741==    by 0x60F9790: FastICPrec&lt;int, double, Kokkos::Serial&gt;::symbolicILU() (shylu_fastic.hpp:323)
==2741==    by 0x60F8245: FastICPrec&lt;int, double, Kokkos::Serial&gt;::initialize() (shylu_fastic.hpp:214)
==2741==    by 0x60F6B54: Ifpack2::Details::Fic&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::initLocalPrec() (Ifpack2_Details_Fic_def.hpp:99)
==2741==    by 0x5F8B251: Ifpack2::Details::FastILU_Base&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::initialize() (Ifpack2_Details_FastILU_Base_def.hpp:277)
==2741==    by 0x5E941CE: Ifpack2::Details::LinearSolver&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::symbolic() (Ifpack2_Details_LinearSolver_def.hpp:171)
==2741==    by 0x5ADBA8D: Ifpack2::AdditiveSchwarz&lt;Tpetra::RowMatrix&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;, Ifpack2::Preconditioner&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt; &gt;::initialize() (Ifpack2_AdditiveSchwarz_def.hpp:1072)
==2741==    by 0x4A9CB4: (anonymous namespace)::Ifpack2AdditiveSchwarz_FastIC_UnitTest&lt;double, int, long long&gt;::runUnitTestImpl(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;, bool&amp;) const (Ifpack2_UnitTestAdditiveSchwarz.cpp:1405)
==2741==    by 0x1633DA13: Teuchos::UnitTestBase::runUnitTest(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) const (Teuchos_UnitTestBase.cpp:62)
==2741==    by 0x1634318E: Teuchos::UnitTestRepository::runUnitTestImpl(Teuchos::UnitTestBase const&amp;, Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) (Teuchos_UnitTestRepository.cpp:539)
==2741==    by 0x163419F5: Teuchos::UnitTestRepository::runUnitTests(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) (Teuchos_UnitTestRepository.cpp:317)
==2741==    by 0x16342B16: Teuchos::UnitTestRepository::runUnitTestsFromMain(int, char**) (Teuchos_UnitTestRepository.cpp:423)
==2741== 
==2741== 4 bytes in 1 blocks are definitely lost in loss record 3 of 5
==2741==    at 0x4C2AC38: operator new[](unsigned long) (vg_replace_malloc.c:433)
==2741==    by 0x6111182: FastILDLPrec&lt;int, double, Kokkos::Serial&gt;::symbolicILU() (shylu_fastildl.hpp:325)
==2741==    by 0x610F9C1: FastILDLPrec&lt;int, double, Kokkos::Serial&gt;::initialize() (shylu_fastildl.hpp:217)
==2741==    by 0x610E1B6: Ifpack2::Details::Fildl&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::initLocalPrec() (Ifpack2_Details_Fildl_def.hpp:99)
==2741==    by 0x5F8B251: Ifpack2::Details::FastILU_Base&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::initialize() (Ifpack2_Details_FastILU_Base_def.hpp:277)
==2741==    by 0x5E941CE: Ifpack2::Details::LinearSolver&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;::symbolic() (Ifpack2_Details_LinearSolver_def.hpp:171)
==2741==    by 0x5ADBA8D: Ifpack2::AdditiveSchwarz&lt;Tpetra::RowMatrix&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt;, Ifpack2::Preconditioner&lt;double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode&lt;Kokkos::Serial, Kokkos::HostSpace&gt; &gt; &gt;::initialize() (Ifpack2_AdditiveSchwarz_def.hpp:1072)
==2741==    by 0x4AB810: (anonymous namespace)::Ifpack2AdditiveSchwarz_FastILDL_UnitTest&lt;double, int, long long&gt;::runUnitTestImpl(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;, bool&amp;) const (Ifpack2_UnitTestAdditiveSchwarz.cpp:1494)
==2741==    by 0x1633DA13: Teuchos::UnitTestBase::runUnitTest(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) const (Teuchos_UnitTestBase.cpp:62)
==2741==    by 0x1634318E: Teuchos::UnitTestRepository::runUnitTestImpl(Teuchos::UnitTestBase const&amp;, Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) (Teuchos_UnitTestRepository.cpp:539)
==2741==    by 0x163419F5: Teuchos::UnitTestRepository::runUnitTests(Teuchos::basic_FancyOStream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;) (Teuchos_UnitTestRepository.cpp:317)
==2741==    by 0x16342B16: Teuchos::UnitTestRepository::runUnitTestsFromMain(int, char**) (Teuchos_UnitTestRepository.cpp:423)
==2741== 
==2741== LEAK SUMMARY:
==2741==    definitely lost: 16 bytes in 4 blocks
==2741==    indirectly lost: 0 bytes in 0 blocks
==2741==      possibly lost: 0 bytes in 0 blocks
==2741==    still reachable: 176 bytes in 1 blocks
==2741==         suppressed: 0 bytes in 0 blocks
==2741== Reachable blocks (those to which a pointer was found) are not shown.
==2741== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2741== 
==2741== For lists of detected and suppressed errors, rerun with: -s
==2741== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
```
I hope this is enough to reproduce the issue. If not, please let me know.

**Comment by jgfouca** [comment]
@cgcgcg , thanks. The shylu memleaks were easy to fix. I'm trying to track down the remaining uninit warnings.

**Comment by cgcgcg** [comment]
Our dashboard is still not posting correctly. The valgrind warnings are no longer in the log files though, so this seems to be fixed. Thanks @jgfouca !
