### ISSUE TITLE
SEACAS configure issue on Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV clean build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1392]
CC: @trilinos/framework 

@gsjaardema There is a failing configure for SEACAS on the serial clean build:

[http://testing.sandia.gov/cdash/viewConfigure.php?buildid=2934238](http://testing.sandia.gov/cdash/viewConfigure.php?buildid=2934238)

Can you suggest the right fix? We can turn off this TPL if necessary. I am not sure what changed that would have caused this in the last few days.

**Comment by gsjaardema** [comment]
It looks like there are two TEST_2 CMND in one of the tests.  The second one should be TEST_3; not sure why this didn't get caught earlier...   I will fix and get propagated through Sierra to Trilinos.

**Comment by gsjaardema** [comment]
This has been fixed in Sierra.  Can by synced over to Trilinos

**Comment by bartlettroscoe** [comment]
This was a result of #1378.  The function CMAKE_PARSE_ARGUMENTS() does a little better checking than the old PARSE_ARGUMENTS() did.  I ran into one case like this with a TriBITS test as well.

I tested all downstream packages before pushing the changes in #1378, but the standard CI build is an MPI build.

@gsjaardema, are these SEACAS tests that only run in a non-MPI Serial build?  If so, why is that?  Most Trilinos packages are set up so that the serial test suite is a strict subset of the test suite that runs when MPI is enabled.  Is that not possible?  If not, why?

**Comment by bartlettroscoe** [comment]
Still failing.  Can we just apply this patch directly to Trilinos GitHub 'develop' to fix the issue and then let the next snapshot of SEACAS from SIERRA write over this?  Otherwise we are never going to have clean "Clean" builds that involve SEACAS and STK with the current integration processes.

If there is no objection I will just do it and provide the commands that I used.  I should be able to use `git format-patch` to pull of that fix off of the SEACAS git reo and then use `git am` to apply it to SEACAS in Trilinos.

**Comment by bartlettroscoe** [comment]
Since there was no objection so I applied the patch as:

```
$ cd Trilinos/
$ git clone git@github.com:gsjaardema/seacas.git
$ cd seacas/
$ git format-patch -1 -o ../../patches/ 2edad04
../../patches/0001-Fix-bad-advanced-test.patch
$ cd ../packages/seacas/
$ git am -p1 ../../../patches/0001-Fix-bad-advanced-test.patch

```

I then ran the checkin-test-sems.sh script with the SERIAL_RELEASE_SHARED_PT build (which reproduced the problem) to test and push:

```
$ ./checkin-test-sems.sh --st-extra-builds=SERIAL_RELEASE_SHARED_PT \
  --no-enable-fwd-packages --enable-packages=SEACAS --do-all --push
```

This pushed the commit 0a3ad89:

```
commit 0a3ad894e719b1d28a0bb2760fb91f622f7790c3
Author: Greg Sjaardema <gsjaardema@gmail.com>
Date:   Mon Jun 5 08:26:09 2017 -0400

    Fix bad advanced test
    
    Build/Test Cases Summary
    Enabled Packages: SEACAS
    Disabled Packages: PyTrilinos,Claps,TriKota
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=8,notpassed=0 (0.26 min)
    1) SERIAL_RELEASE_SHARED_PT => passed: passed=15,notpassed=0 (0.68 min)

M       packages/seacas/libraries/aprepro_lib/CMakeLists.txt
```

NOTE: The modified subpackages `SEACASAprepro_lib` does not have any tests in an MPI build so I had to explicitly enable all of SEACAS to get the standard CI build MPI_RELEASE_DEBUG_SHARED_PT to pass with some tests.

NOTE: I did not test downstream packages because this commit only changed a test in SEACAS.

Hopefully this comment can provide a template process for fixing an issue like this in the future involving these snapshotted packages.

I am putting into review until it is confirmed by the "Clean"build Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV build tomorrow (6/15/2017).

**Comment by bartlettroscoe** [comment]
SEACAS is now passing in the "Clean" build `Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV` today:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2948431

This should likely be kept open until SEACAS is snapshotted from Sierra.

Therefore, putting into review

**Comment by bmpersc** [comment]
SEACAS was updated in Trilinos on June 15th and there have been no reports of this issue coming back since then so I am closing.
