### ISSUE TITLE
Sacado Warning in gcc 7.2

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#2205]
Sacado is producing the following warning on gcc 7.2.  It writes this probably a hundred times during normal compile of panzer making it hard to find important warnings. 

```
[368/895] Building CXX object packages/intrepid2/unit-test/Discretiz...s_HDIV_HEX_In_FEM_Serial_Test_01_SFadSFad.dir/test_01_SFadSFad.cpp.
In file included from /ascldap/users/rppawlo/junk/Trilinos/packages/sacado/src/Kokkos_ViewFactory.hpp:36:0,
                 from /ascldap/users/rppawlo/junk/Trilinos/packages/intrepid2/unit-test/Discretization/Basis/HDIV_HEX_In_FEM/Serial/test_01_SFadSFad.cpp:49:
/ascldap/users/rppawlo/junk/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp: In instantiation of ‘class Kokkos::Impl::ViewMapping<Kokkos::ViewTraits<Sacado::Fad::SFad<double, 10>*******, Kokkos::Serial>, void>’:
/ascldap/users/rppawlo/junk/Trilinos/packages/kokkos/containers/src/Kokkos_DynRankView.hpp:443:15:   required from ‘class Kokkos::Experimental::DynRankView<Sacado::Fad::SFad<double, 10>, Kokkos::Serial>’
/ascldap/users/rppawlo/junk/Trilinos/packages/intrepid2/unit-test/Discretization/Basis/HDIV_HEX_In_FEM/test_01.hpp:277:31:   required from ‘int Intrepid2::Test::HDIV_HEX_In_FEM_Test01(bool) [with OutValueType = Sacado::Fad::SFad<double, 10>; PointValueType = Sacado::Fad::SFad<double, 10>; DeviceSpaceType = Kokkos::Serial]’
/ascldap/users/rppawlo/junk/Trilinos/packages/intrepid2/unit-test/Discretization/Basis/HDIV_HEX_In_FEM/Serial/test_01_SFadSFad.cpp:66:112:   required from here
/ascldap/users/rppawlo/junk/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:685:46: warning: enum constant in boolean context [-Wint-in-bool-context]
         template append<( FadStaticDimension ? FadStaticDimension + 1 : 0 )>::type
                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by etphipp** [comment]
I just pushed a change that should resolve it.  Let me know.

**Comment by rppawlo** [comment]
Still getting a ton of warnings but all from one single line in the fad storage. Fixing this line should get them all.

```
/ascldap/users/rppawlo/junk/Trilinos/packages/intrepid2/unit-test/Discretization/Basis/HVOL_LINE_Cn_FEM/test_01.hpp:266:30:   required from ‘int Intrepid2::Test::HVOL_LINE_Cn_FEM_Test01(bool) [with OutValueType = Sacado::Fad::SFad<double, 2>; PointValueType = double; DeviceSpaceType = Kokkos::Serial]’
/ascldap/users/rppawlo/junk/Trilinos/packages/intrepid2/unit-test/Discretization/Basis/HVOL_LINE_Cn_FEM/Serial/test_01_SLFadDouble.cpp:66:108:   required from here
/ascldap/users/rppawlo/junk/Trilinos/packages/sacado/src/Sacado_Fad_ViewStorage.hpp:175:26: warning: enum constant in boolean context [-Wint-in-bool-context]
         return sz_.value ? dx_[ stride_one ? i : i * stride_.value ] : T(0.);
                ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by etphipp** [comment]
OK, just pushed another change.

**Comment by rppawlo** [comment]
Awesome - that did it! Thanks @etphipp !
