### ISSUE TITLE
Test Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial[_MPI_4] fails standard CI build and several other builds including the ATDM build Trilinos-atdm-sems-gcc-7-2-0

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2254]
**CC:** @trilinos/stokhos, @trilinos/framework

## Next Action Status

@csiefer2's commits 115e829 and 859157d were reverted with the commit 61b3d9677.  Next: @csiefer2 to fix the problem and push new commits that pass the standard CI build and the auto PR build ...

## Description

The test `Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial_MPI_4` (and the non-MPI version `Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial`) is failing in the new `Trilinos-atdm-sems-gcc-7-2-0` build and several other builds a shown at:

* https://testing-vm.sandia.gov/cdash/testSummary.php?project=1&name=Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial_MPI_4&date=2018-02-18

This started failing in the standard CI build starting with the build 20180215-2003-Continuous as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now
* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

This is also breaking all of the "Clean" builds as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-02-18

The failure is showing:

```
*** glibc detected *** /scratch/rabartl/Trilinos.base/SEMSCIBuild/BUILD/packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial.exe: double free or corruption (!prev): 0x00000000029c7b80 ***
```

Since when does glibc detect double delete and abort?

**Comment by bartlettroscoe** [comment]
Because this is breaking the standard CI build (and therefore the checkin-test-sems.sh scirpt) and the "Clean" builds and therefore likely breaking all of the automated PR testing builds, this test should be disabled ASAP.

**Comment by etphipp** [comment]
Isn't the proper thing to do to revert the commit that broke the builds rather than disable the test?

**Comment by bartlettroscoe** [comment]
> Isn't the proper thing to do to revert the commit that broke the builds rather than disable the test?

If reverting a single commit fixes this then great.  But that might require reverting commits that came after it. 

Looking at the commit log for 115e8299e2c1aae3f1d0b47b34289f3e9ea502e3 it looks like @csiefer2 ran the checkin-test-sems.sh script to push but did not enable downstream packages. Therefore, it looks like he never actually rand the Stokhos tests.

I will go ahead and try reverting the commit 115e8299e2c1aae3f1d0b47b34289f3e9ea502e3 and running the checkin-test-sems.sh script to push.  Hopefully that will go smoothly.

**Comment by bartlettroscoe** [comment]
@etphipp is correct.  It was those commits that broke this test as shown at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3316847#!#note1

which is two commits:

```
115e829:  MueLu: Missed a map replacement
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Thu Feb 15 12:54:27 2018 -0700

M	packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp

859157d:  MueLu: Fixing something I missed w/ the vector cache
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Thu Feb 15 09:49:38 2018 -0700

M	packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
```

Therefore, to be safe, I will revert the commit 115e829 and 859157d to be safe.

**Comment by bartlettroscoe** [comment]
I just pushed the commit:

```
commit 61b3d9677c4f7a24a1069c71d189a1b5c2ed3c2b
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Feb 19 09:53:56 2018 -0700

    Revert 'MueLu: Missed a map replacement' and 'Fixing something I missed w/ the vector cache' (#2254)
    
    This reverts commit 115e8299e2c1aae3f1d0b47b34289f3e9ea502e3.
    This reverts commit 859157d7d1167e6d95c1f610f2b519056505a357.
    
    These two commits were pushed in the CI iteration that first broke the test
    Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial[_MPI_4] (see #2254).  I am not
    sure which commit broke this or if these commits must go together, I am
    reverting both of them.
    
    Build/Test Cases Summary
    Enabled Packages: MueLu
    Disabled Packages: PyTrilinos,Claps,TriKota
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=496,notpassed=0 (65.71 min)

M       packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
```

with the testing results:

```
100% tests passed, 0 tests failed out of 496

Label Time Summary:
MueLu                = 317.06 sec (83 tests)
Panzer               = 577.52 sec (154 tests)
Piro                 =  27.50 sec (12 tests)
ROL                  = 780.42 sec (151 tests)
Stokhos              =  97.45 sec (75 tests)
TrilinosCouplings    =  56.43 sec (24 tests)

Total Test time (real) = 342.92 sec
```

That should clear up this failure.   We will see what the CI build does with this and wait and see what happens with the other builds on CDash tomorrow morning.

**Comment by bartlettroscoe** [comment]
This test is now passing in the most recent CI iteration shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3395349
* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3324077

See the newly passing test at:

* https://testing.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3395353
* https://testing-vm.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3324081

(That link on testing-vm.sandia.gov should work for 6 months!)

Therefore, I guess we can close this issue.

@csiefer2,

You can revert this merge commit locally and then make changes to fix the failing Stokhos test with:

```
$ cd Trilinos
$ git pull
$ git revert 61b3d9677c4f7a24a1069c71d189a1b5c2ed3c2b
```

And then just make sure and run the checkin-test-sems.sh script, letting it test all of the downstream packages with:

```
$ ./checkin-test-sems.sh --do-all --push
```

**Comment by csiefer2** [comment]
Can someone explain to me what you did or didn't do?

**Comment by bartlettroscoe** [comment]
> Can someone explain to me what you did or didn't do?

I pushed the commit 61b3d9677c4f7a24a1069c71d189a1b5c2ed3c2b which reverted your changes (do a log on the commit and it should be obvious).  You just need to revert that commit (as described above) and fix the failures.  Also, technically, a test should be added to the native MueLu test suite that exposes this defect before you fix the failure.

**Comment by csiefer2** [comment]
Thanks for the explaination.

**Comment by bartlettroscoe** [comment]
@csiefer2, just let the checkin-test-sems.sh script test downstream packages in the future and it should avoid situations like this.  That is, just run:

```
$ ./checkin-test-sems.sh --do-all --push
```

I know that can take a lot of computer time but it is worth it.

NOTE: And apparently, using the checkin-test-sems.sh script is safer than relying on the automated PR system currently (see #2264 and #2171).  Someone needs to explain how those automated PR tests passed and yet MueLu is broken everywhere.

**Comment by csiefer2** [comment]
For future reference, please do not close issues associated with code reverts.... If github emails are down (like they seem to be with some frequency) then those of us who rely on notification emails will never know you reverted code.

**Comment by mhoemmen** [comment]
I'm w/ @csiefer2 here -- it's easy to get overwhelmed w/ notifications even if e-mails are working, so leaving the issue open can help us realize that something went wrong.  The developer who originally pushed the reverted code can choose how to respond -- either to revise and fix the reverted code, or to accept the revert.

**Comment by bartlettroscoe** [comment]
> For future reference, please do not close issues associated with code reverts.... If github emails are down (like they seem to be with some frequency) then those of us who rely on notification emails will never know you reverted code.

Fair enough.

**Comment by etphipp** [comment]
Chris and I talked and we think we know what is wrong.  The particular test that is failing is a test that uses the "mean-based preconditioner", where MueLu is given a matrix to build the preconditioner from where the scalar type has a different size (as in bytes) from the scalar that is used to solve the linear system.  Since MueLu now creates these vectors at hierarchy setup-time, these vectors are created with the wrong scalar size (they need to be the same size as the scalars used in the linear system).

Since MueLu can recreate these vectors during iterate if the number of right-hand-sides changes, a simple solution would be for MueLu to also check if the size of the scalar has changed.  Stokhos has a function to get this size from a Kokkos::View, but unfortunately that function doesn't exist outside of Stokhos.  A simple solution would be for MueLu to define a simple template function with a default implementation that will work for anybody:
```
namespace Muelu {
  template <typename ViewType>
  unsigned view_scalar_dimension(const ViewType& v) { return 1; }
} 
```
Then I can provide an overload of that in Stokhos that computes the scalar size correctly.  And instead of view's it could be passed Tpetra multivectors if that is more convenient.

**Comment by csiefer2** [comment]
@etphipp I suspect this should live in Xpetra, not MueLu.  I'd rather work on MultiVectors since we have to manage use of Kokkos very carefully in MueLu (for Windows support, since Kokkos doesn't compile w/ Visual Studio).

How about:

namespace Xpetra {
  template <typename MultiVectorType>
  unsigned multivector_scalar_dimension(const MultiVectorType& v) { return 1; }
}

**Comment by etphipp** [comment]
Sure, that will work.  I presume MultiVectorType will be an Xpetra multi vector?

**Comment by csiefer2** [comment]
That would be a rational way to do it.

**Comment by bartlettroscoe** [comment]
This has been fixed for a long time.  You can see it is currently passing in the Trilinos-atdm-sems-gcc-7-2-0 build today at:

* https://testing.sandia.gov/cdash/testDetails.php?test=44974614&build=3410611

and in the CI build at:

* https://testing.sandia.gov/cdash/testDetails.php?test=44972175&build=3410567

I am closing this as complete.

Thanks for the fix!

**Comment by csiefer2** [comment]
This is not fixed.  I'm still tracking down the original issue that the revert is hiding.

**Comment by bartlettroscoe** [comment]
> This is not fixed. I'm still tracking down the original issue that the revert is hiding.

@csiefer2, 

Oops, sorry about that.  I forgot that this was a revert and not the disable of the test.

I assigned this to you and added the "Next Action Status" field to make the current status clear.

Thanks for catching my mistake (just trying to clean out issues that have been resolved).

**Comment by csiefer2** [comment]
No problem :)

**Comment by csiefer2** [comment]
Checkin script running... fingers crossed :)

**Comment by csiefer2** [comment]
Sticking a fork in this.
