### ISSUE TITLE
Failing ROL tests on ATDM cee-rhel6 intel-18 build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3914]
CC: @trilinos/Rol, @rppawlo (Trilinos Nonlinear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
 
## Next Action Status

Cause is a defect LAPACK GEEV function with intel-18.0.2 in MKL.  Next: Try out intel-18.0.5 update on CEE RHEL6 env.  But first, we need to remove usage of SPARC modules in 'cee-rhel6' env (see [TRIL-246](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-246)).
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6-intel-18.0.2-mpich2-3.2-serial-static-opt&field2=testname&compare2=65&value2=ROL_&field3=site&compare3=61&value3=cee-rhel6&field4=buildstarttime&compare4=84&value4=2018-11-22T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-11-21T00%3A00%3A00) the tests:
* [ROL_example_poisson-inversion_example_01_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=59772883&build=4198733)
* [ROL_test_function_DerivativeCheck_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=59772877&build=4198733)
* [ROL_test_step_TrustRegion_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=59772880&build=4198733)

are failing in the build:
* Trilinos-atdm-cee-rhel6-intel-18.0.2-mpich2-3.2-serial-static-opt

the links above will take you to the test output

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&field2=testname&compare2=65&value2=ROL_)

## Steps to Reproduce

One should be able to reproduce this failure on a machine with a cee rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for a machine with a cee rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-cee-rhel6-intel-18.0.2-mpich2-3.2-serial-static-opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Rol=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j16
```

**Comment by dridzal** [comment]
@fryeguy52 @rppawlo @bartlettroscoe 

After talking to @hkthorn , I believe that this is due to a bad MKL build with this compiler.  The segfault is in LAPACK's GEEV, see ROL_HelperFunctions.hpp,

```
    int lwork = 4*n;
    std::vector<Real> work(lwork, 0);
    int info = 0;
    lapack.GEEV(jobvl, jobvr, n, &mymat(0,0), n, &real[0], &imag[0], vl, ldvl, vr, ldvr, &work[0], lwork, &info);
```

@hkthorn is looking to provide definitive evidence, related to Issue #3497 .

If this suspicion is confirmed, we need to push back and get Intel MKL fixed (or not use it), otherwise this will keep coming up.  We shouldn't have to rewrite our codes to find an optimal workspace size for LAPACK just so the MKL routines don't crash.  In the above example, the workspace size was set precisely according to the recommendations given in LAPACK's documentation.

I think that in the long term we need to develop comprehensive LAPACK testing that is prerequisite to building Trilinos.

**Comment by dridzal** [comment]
As mentioned in #3497, this is a known MKL bug, see bug fix MKLD-3796 here:

https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-bug-fixes-list

Should we close this issue?

**Comment by bartlettroscoe** [comment]
@dridzal said:

> As mentioned in #3497, this is a known MKL bug, see bug fix MKLD-3796 here:
> 
> https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-bug-fixes-list

@dridzal, as I just mentioned in https://github.com/trilinos/Trilinos/issues/3497#issuecomment-441687029, can we make a similar change to calling this LAPACK routine and make this error go away? 


> Should we close this issue?

Can't close the issue while the tests are still failing.  We either need to make the tests pass (as suggested in https://github.com/trilinos/Trilinos/issues/3497#issuecomment-441687029) or they need to be disabled.

Not that I think this is the default production env on 'trinity' so I think that would need to be upgraded as well to fix this.

Otherwise, let us know and we can disable this test (but leave this issue open until the problem can be resolved).

**Comment by dridzal** [comment]
@bartlettroscoe 
We really need to push back and get this fixed for mutrino and trinity.  GEEV is a fundamental LAPACK routine, and while we can hack a bunch of Trilinos packages to make (unnecessary) calls to get the workspace sizes "just right", this will remain an issue for Trilinos' TPLs and other scientific computing libraries.  This needs to be publicized widely, beyond the Trilinos community.

**Comment by bartlettroscoe** [comment]
I added the label "ATDM Env Issue" since this is really a problem with the env, not Trilinos code or tests.

**Comment by bartlettroscoe** [comment]
@hkthorn and @dridzal,

FYI: I was told by the 'mutrino' admins that Intel 18.0.5 should be installed on 'the system (as module `intel/18.0.5`) which should have this MKL bug fix.  However, I was not able to load this module.  I have asked for clarification on how to load this module so that I can try it out.

**Comment by bartlettroscoe** [comment]
CC: @srajama1, @rppawlo 

@dridzal, note that getting a updated to Intel 18 on 'mutrino' is a multi-lab effort (because 'mutrino' has to match 'trinity', 'trinitite', etc.)  Therefore, as we discussed in the ATDM PI meeting today, we should either disable these tests in the build for now or implement the same workaround that @hkthorn did in PR #3951.  

Should we just disable this test for now and mark it with "Disabled Tests"?

**Comment by dridzal** [comment]
I'm just afraid that a lot of these temporarily disabled tests will never get re-enabled after the machines are fixed.  I think it's a better idea to allow failing tests --keeping track of the total count--  as a constant reminder that this is a pretty big issue.

**Comment by bartlettroscoe** [comment]
> I'm just afraid that a lot of these temporarily disabled tests will never get re-enabled after the machines are fixed. I think it's a better idea to allow failing tests --keeping track of the total count-- as a constant reminder that this is a pretty big issue.

Lots of way to remember which tests are disabled:

* [GitHub Issues query](https://github.com/trilinos/Trilinos/issues?q=label%3AATDM+label%3A%22Disabled+Tests%22+is%3Aopen+label%3AROL)

* [Grepping the tweaks files](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos#ATDMBuildsofTrilinos-AddressingfailuresandPromoting)

* Set up an automated email that reminds you ever X day/weeks that a test is disabled.

All better than letting the test fail.

**Comment by dridzal** [comment]
Sure, but whose responsibility is it to re-enable them?  Someone must be watching the status of the required fixes to know that this can be done.  Maybe a better policy would be to disable the tests for a fixed amount of time (e.g., two weeks, a month, three months, etc.), so that there is a guarantee of re-enabling.  Do we have such infrastructure?

**Comment by bartlettroscoe** [comment]
@dridzal 

This is disabling a few ROL tests on just one build.  You loose essentially no testing.  If this was disabling thse ROL tests on all builds, that would be a different story.  The risk for forgetting to re-enable these is almost zero.

Another approach that we could handle systematically is to use the new CTest/CDash DISABLED property:

* https://cmake.org/cmake/help/v3.12/prop_test/DISABLED.html

That way you can see them on CDash but then we can filter them out of our analysis tools and processes.

Reasonable compromise?

I am getting feedback that people really hate seeing "red" on the dashboard.

**Comment by dridzal** [comment]
That sounds reasonable.  Will the tests show as "Not Run"?  That would be a convenient constant reminder.

**Comment by bartlettroscoe** [comment]
> Will the tests show as "Not Run"? That would be a convenient constant reminder.

@dridzal, yes, these would show up a "Not Run" tests.  One problem with this approach currently is that the main dashboard would always show these as "Not Run" tests.  We have a backlog item for Kitware to support filtering out these tests if we desire:

* https://gitlab.kitware.com/snl/project-1/issues/15

But we can upgrade out Python tool in #2933 to be able to handle those tests.

But the problem is that unless you are personally looking at the CDash site, you will never look at these tests, so I don't think you would notice.  For example, no one notices these tests currently failing on CDash.  It is only this GitHub Issue that does that.

**Comment by bartlettroscoe** [comment]
FYI: Just heard that they installed the Intel 18.0.5 update on the CEE LAN.  I just looked at `module avail` and it shows:

```
sierra-devel/intel-18.0.5-intelmpi-2018.4                                                                                                                                           
sierra-devel/intel-18.0.5-intelmpi-5.1                                                                                                                                              
sierra-devel/intel-18.0.5-intelmpi-5.1-fat                                                                                                                                          
sierra-devel/intel-18.0.5-openmpi-1.10.2                                                                                                                                            
sierra-devel/intel-18.0.5-openmpi-2.1.5                                                                                                                                             
```

@fryeguy52, I think that means that we can test out the updated intel-18.0.5 MKL on the CEE LAN.  But to do this, we have to move away from the SPARC modules as per https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-246.

**Comment by rppawlo** [comment]
@bartlettroscoe - can we close this? Were the rol tests disabled or were they fixed with the intel compiler upgrade?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe - can we close this? Were the rol tests disabled or were they fixed with the intel compiler upgrade?

No, the tests are still failing in the build `Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt` shown, for example, yesterday shown here:

* https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4409860

The next action is to true updated intel-18.0.5 on the CEE RHEL6 machines.  But before we can do that, we need to stop using SPARC modules (see https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-246).  I will update the "Next Action Status" for this.

**Comment by bartlettroscoe** [comment]
FYI: I updated the link in the "Current Status" section above.

**Comment by bartlettroscoe** [comment]
With the merge of PR #4579 on 3/7/2019 which switches to use Intel MKL 18.0.5 (upgraded from 18.0.2), these ROL tests have been passing for the last three days as shown in the table below.

Closing this as complete.

<h3><font color="green">Tests with issue trackers Passed: twip=8</font> (on 2019-13-10)</h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec­utive Pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">cee-rhel6</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=site&amp;compare2=61&amp;value2=cee-rhel6&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-03-11T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-02-09T00:00:00">Trilinos-atdm-cee-rhel6_­intel-18.0.2_­mpich2-3.2_­openmp_­static_­opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=70013345&amp;build=4691339">ROL_­example_­poisson-inversion_­example_­01_­MPI_­1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=70013345&amp;build=4691339"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_example_poisson-inversion_example_01_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="green">3</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_example_poisson-inversion_example_01_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="red">27</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_example_poisson-inversion_example_01_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="green">3</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3914">#3914</a></td>
</tr>

<tr>
<td align="left">cee-rhel6</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=site&amp;compare2=61&amp;value2=cee-rhel6&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-03-11T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-02-09T00:00:00">Trilinos-atdm-cee-rhel6_­intel-18.0.2_­mpich2-3.2_­openmp_­static_­opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=70013337&amp;build=4691339">ROL_­test_­function_­DerivativeCheck_­MPI_­1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=70013337&amp;build=4691339"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_test_function_DerivativeCheck_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="green">3</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_test_function_DerivativeCheck_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="red">27</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_test_function_DerivativeCheck_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="green">3</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3914">#3914</a></td>
</tr>

<tr>
<td align="left">cee-rhel6</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=site&amp;compare2=61&amp;value2=cee-rhel6&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-03-11T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-02-09T00:00:00">Trilinos-atdm-cee-rhel6_­intel-18.0.2_­mpich2-3.2_­openmp_­static_­opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=70013344&amp;build=4691339">ROL_­test_­step_­TrustRegion_­MPI_­1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=70013344&amp;build=4691339"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_test_step_TrustRegion_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="green">3</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_test_step_TrustRegion_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="red">27</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=ROL_test_step_TrustRegion_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-11T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-09T00:00:00"><font color="green">3</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3914">#3914</a></td>
</tr>

</table>
