### ISSUE TITLE
Thyra:  Conflict definition of class CopyMultiVectorViewBack 

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#5494]
## Bug Report
@trilinos/\<Thyra\>

### Description
class CopyMultiVectorViewBack has been defined in file Thyra_TpretraVectorSpace_def.hpp and Thyra_VectorSpaceDefaultBase_def.hpp with different template members. It produces compile error  "redeclared with 4 template parameters" and "wrong number of template arguments (4, should be 1)" in ubuntu with gcc compiler.

**Comment by mhoemmen** [comment]
@trilinos/thyra

**Comment by bartlettroscoe** [comment]
Why did PR testing not catch this?  Where there at least warnings in the PR testing build?

**Comment by cgcgcg** [comment]
@bartlettroscoe I don't see any warnings in the logs from the autotester, and warnings-as-errors also did not catch this. This shouldn't be difficult to fix, but it's odd that we did not see it. @hillyuan would you be able to post your configuration? Maybe it contains a combination of configure options that is not well tested?

**Comment by cgcgcg** [comment]
@hillyuan I pushed a fix. Could you verify that this fixed the issue for you? Since this did not seem to affect any of our tests, it would be good to know that I actually got it.

**Comment by hillyuan** [comment]
@cgcgcg It is not resolved yet. Same problem arose both in WSL and Ubuntu.  Following is my building script and error log. Hope it would help.
   There are two CopyMultiVectorViewBack definition right now. Maybe we need to delete one of them.


***
rm -f CMakeCache.txt
cmake ..  \
  -DCMAKE_INSTALL_PREFIX:FILEPATH="/usr/local/Trilinos" \
  -DCMAKE_BUILD_TYPE:STRING=RELEASE \
  -DTrilinos_ENABLE_EXAMPLES:BOOL=ON  \
  -DTrilinos_ENABLE_TESTS:BOOL=ON \
  -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_HDF5=ON   \
  -DHDF5_LIBRARY_DIRS=/usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib   \
  -DHDF5_INCLUDE_DIRS=/usr/lib/x86_64-linux-gnu/hdf5/openmpi/include   \
  -DTrilinos_ENABLE_Fortran=OFF \
  -DTrilinos_ENABLE_SEACAS=OFF \
  -DTrilinos_ENABLE_Anasazi=ON \
  -DTrilinos_ENABLE_Zoltan=ON \
  -DTrilinos_ENABLE_Panzer=ON \
***
In file included from /mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace.hpp:45:0,
                 from /mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraThyraWrappers_def.hpp:47,
                 from /mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraThyraWrappers.hpp:45,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp:85,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp:78,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp:53,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_IteratorOps.hpp:53,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_IteratorOps.cpp:47:
/mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp: At global scope:
/mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp:118:7: error: redeclared with 4 template parameters
 class CopyMultiVectorViewBack {
       ^
In file included from /mnt/c/ubuntu/newTrilinos/build/packages/thyra/core/src/Thyra_VectorSpaceDefaultBase.hpp:2:0,
                 from /mnt/c/ubuntu/newTrilinos/packages/thyra/core/src/support/operator_vector/client_support/Thyra_DefaultProductVectorSpace_decl.hpp:46,
                 from /mnt/c/ubuntu/newTrilinos/build/packages/thyra/core/src/Thyra_DefaultProductVectorSpace.hpp:1,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp:78,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp:78,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp:53,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_IteratorOps.hpp:53,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_IteratorOps.cpp:47:
/mnt/c/ubuntu/newTrilinos/packages/thyra/core/src/support/operator_vector/client_support/Thyra_VectorSpaceDefaultBase_def.hpp:79:7: note: previous declaration ‘template<class Scalar> class Thyra::CopyMultiVectorViewBack’ used 1 template parameter
 class CopyMultiVectorViewBack {
       ^
In file included from /mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace.hpp:45:0,
                 from /mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraThyraWrappers_def.hpp:47,
                 from /mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraThyraWrappers.hpp:45,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp:85,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp:78,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp:53,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_IteratorOps.hpp:53,
                 from /mnt/c/ubuntu/newTrilinos/packages/xpetra/sup/Utils/Xpetra_IteratorOps.cpp:47:
/mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp: In member function ‘Teuchos::RCP<Thyra::MultiVectorBase<Scalar> > Thyra::TpetraVectorSpace<Scalar, LocalOrdinal, GlobalOrdinal, Node>::createMembersView(const RTOpPack::SubMultiVectorView<Scalar>&) const’:
/mnt/c/ubuntu/newTrilinos/packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp:195:84: error: wrong number of template arguments (4, should be 1)
     Teuchos::rcp(new CopyMultiVectorViewBack<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::rcpFromRef(*mv),raw_mv)),
***

**Comment by cgcgcg** [comment]
@hillyuan Which branch of Trilinos are you on? If it's master, you might actually have to wait for a day or so until the fix makes it there from develop.

**Comment by hillyuan** [comment]
@cgcgcg  I use master. I see, I would try develop!

**Comment by cgcgcg** [comment]
@hillyuan Your call. Develop is typically only a day or so ahead of master, so you should be getting the patch tomorrow on master..

**Comment by hillyuan** [comment]
Alright in develop confirmed ! Thanks @cgcgcg

**Comment by cgcgcg** [comment]
Great! Thanks for checking!
