### ISSUE TITLE
MueLu: Notay unit tests fail in parallel

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#7860]
## Bug Report
@trilinos/muelu 

### Description

When running the MueLu unit tests with Tpetra enabled (and Epetra disabled), the units tests pass on 1 MPI rank, but fail on 4 MPI ranks. In particular, the test `NotayAggregation_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_InitialAggregation2D_UnitTest` fails with this screen output:
```bash
2: 94. NotayAggregation_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_InitialAggregation2D_UnitTest ... 
2:  version: MueLu development
2:  numUnaggregatedNodes = 0 == 0 = 0 : passed
2:  sizes[i] = 2 == expected = 2 : passed
2:  sizes[i] = 2 == expected = 2 : passed
2:  sizes[i] = 2 == expected = 2 : passed
2:  sizes[i] = 1 == expected = 1 : passed
2:  NOTE: Global reduction shows failures on other processes!
2:  (rerun with --output-to-root-rank-only=-1 to see output
2:  from other processes to see what process failed!)
2:  NOTE: Unit test failed on processes = {1, 2}
2:  (rerun with --output-to-root-rank-only=<procID> to see output
2:  from individual processes where the unit test is failing!)
2:  [FAILED]  (0.000335 sec) NotayAggregation_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_InitialAggregation2D_UnitTest
2:  Location: /ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/test/unit_tests/NotayAggregationFactory.cpp:126
```
All other Notay unit tests pass.

### Additional Information

I have set the `-D Teuchos_GLOBALLY_REDUCE_UNITTEST_RESULTS:BOOL=ON` option. When setting this option to `OFF`, all unit tests pass. 

### Steps to Reproduce
1. SHA1:  855be51cb9146b75f54f89589893b89a988adb1c
1. Configure script: [do-configure-trilinos_muelu_tpetra.txt](https://github.com/trilinos/Trilinos/files/5089155/do-configure-trilinos_muelu_tpetra.txt)
1. Configure log: [configure.txt](https://github.com/trilinos/Trilinos/files/5089176/configure.txt)
1. Build log: build passes just fine.
1. Navigate in MueLu's unit test directory and run `ctest -R UnitTests`
1. Run log: see above

**Comment by mayrmt** [comment]
@csiefer2, you added the Notay aggregation in the first place (PRs #6865 and #7291). Do you have any more insight into this error?

**Comment by mayrmt** [comment]
Fix has been merged to `master` via PR #7899. Closing.

**Comment by cgcgcg** [comment]
Is this actually fixed? Looking at the dashboard, it seems that it's still failing in a couple of builds.

**Comment by mayrmt** [comment]
@cgcgcg It was merged to `master` as of today. So, wait until tomorrow and check the dashboard again. If it's still failing then, let's reopen.

**Comment by mayrmt** [comment]
@cgcgcg Dashboard as of last night seems to not show this test to be failing: https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2020-08-26&subproject=MueLu

**Comment by cgcgcg** [comment]
I was going to show this as an example that the issue is still there: https://testing.sandia.gov/cdash/test/27665978
But instead, it looks like several of our build are stuck on some old SHA :-/

**Comment by mayrmt** [comment]
I leave it up to you to reopen, if we're not sure, whether this has really been fixed. I have to admit, that I currently don't have a clear overview over the different dashboards.

**Comment by mayrmt** [comment]
@cgcgcg  I had another look at the dashboard (https://testing.sandia.gov/cdash/index.php?subproject=MueLu&project=Trilinos) and it seems that the Notay tests is not failing anymore.

**Comment by cgcgcg** [comment]
Yup, Jonathan fixed our testing :-)
