### ISSUE TITLE
Belos:  memory consumption

### ISSUE THREAD

**Issue by david8dixon** [trilinos/Trilinos#8627]
## Question
@trilinos/\<belos\>

I am tracking down memory consumption in a library and when using the GMRES solver in Belos (and aztecOO) intel vtune suggests that there an allocation of 130 MB per rank that it attributes to libopenblas. Looking at the call stack, this originates in trilinos. 

I have reproducer that captures this behavior and what is interesting is the allocation size is independent of the operator/vector size. I could have a 10 element vector or a 100000 element vector and it doesn't change the libopenblas allocation. Another thing to point out is that vtune suggest that for a few ranks out of 30 this memory is not deallocated. I have not verified this with a memory leak tool but I will look into that next. 

My question is whether anyone else has observed this and what can we do to better understand this allocation? Is it real or is the profiler lying? Should we consider a different blas library?

**Comment by mayrmt** [comment]
@trilinos/belos

**Comment by jhux2** [comment]
Maybe @jjellio has seen this?

**Comment by jjellio** [comment]
Sorry this slipped through my message.

I haven't used OpenBLAS too much. We looked into Belos MVTraits a while back and checked allocations.  Do you know which operations is allocating? (which openblas routine?). We had a pretty good handle on Tpetra's memory use with basic linear algebra (hopefully we haven't missed a regression there).

Something to watch for with OpenBLAS is that it usually uses OpenMP threads.  You could try setting OMP_NUM_THREADS=1 or OPENBLAS_NUM_THREADS=1. It could be you are getting whacky memory due to some multithread workspace allocations.

**Comment by david8dixon** [comment]
I am having trouble getting any meaningful symbol information through
vtune. So I can't say precisely what operation is allocating right now. I
am using a spack RelWithDebInfo build (perhaps I need a Debug build). We
typically set OMP_NUM_THREADS=1 but I haven't tried looking at
OPENBLAS_NUM_THREADS. I will keep profiling to see if I can find anything
helpful. I was just hoping that maybe someone else had pinned this down
before.

**Comment by david8dixon** [comment]
I attached a screen shot showing the profile result that I am referencing. I can't seem to get vtune to give any further information on the LOC in open blas that is allocating. As you can see in the profile the allocation is 128 MB and this is constant as I vary operator/vector size and the number of restarts. When I profile over multiple ranks some ranks have a alloc/dealloc delta of 128 MB and others do not.

![profile](https://user-images.githubusercontent.com/15673912/106172075-98468080-614f-11eb-9d4c-b81dab6bbd35.png)
![allocating_code](https://user-images.githubusercontent.com/15673912/106172083-9c729e00-614f-11eb-80d6-82f328aeb5f9.png)

**Comment by jjellio** [comment]
OpenBLAS does allocate memory in gemm
https://github.com/xianyi/OpenBLAS/blob/develop/interface/gemm.c

This may get resolved by calling the function twice. I suspect they use a memory pool for temporary scratch and you are seeing the first allocation. Ideally, you'd expect them to deallocate their memory (usually atexit() ). It could be that vtune isn't understanding memory free'd during the exit process.

That said, 128MB seems pretty large given the size of main program. I very likely could be that they are allocating 1MB x num_threads (or something like that). If you have numactl available or your MPI is built properly you can mask out extra cores so your program will only see X number of CPUs - that usually will trick the libraries into allocating substantially less memory (since they anticipate less possible threads)

`numactl -C 0 ./prog.exe` would give hide all 'cpus' except 0.

With openmpi `mpirun -map-by core:pe=1 -bind-to core --report-bindings ./prog.exe`

The prior stuff is just setting bindings so that CPUs get hidden - it is very impactful for libraries that support OpenMP/threads.

**Comment by david8dixon** [comment]
So after profiling with the bindings that you suggested I still see the same allocation. Interestingly intel aps reports the following for memory usage (roughly 1/2 of what vtune reports):

 Memory Footprint:
 Resident:
       Per node:
           Peak resident set size    :           63.52 MB 
           Average resident set size :           63.52 MB
       Per rank:
           Peak resident set size    :           63.52 MB (rank 0)
           Average resident set size :           63.52 MB
 Virtual:
       Per node:
           Peak memory consumption    :          435.74 MB 
           Average memory consumption :          435.74 MB
       Per rank:
           Peak memory consumption    :          435.74 MB (rank 0)
           Average memory consumption :          435.74 MB


and using the following:
```
valgrind --tool=massif --pages-as-heap=yes --massif-out-file=massif.out
grep mem_heap_B massif.out | sed -e 's/mem_heap_B=\(.*\)/\1/' | sort -g | tail -n 1
```
gives 416 MB. One way or another it seems like openblas is allocating quite a lot of memory. I am going to attempt a build with MKL to see if that makes any difference.

**Comment by david8dixon** [comment]
So now it gets more interesting. Using intel-MKL blas we get the following from vtune memory-consumption collection:

<img width="1504" alt="Screen Shot 2021-01-29 at 12 39 40 PM" src="https://user-images.githubusercontent.com/15673912/106320003-7e7c6a80-622f-11eb-9df5-b56e68fd7c28.png">

aps gives the following

```
 Memory Footprint:
 Resident:
       Per node:
           Peak resident set size    :           66.57 MB (node sn109.localdomain,s.*)
           Average resident set size :           66.57 MB
       Per rank:
           Peak resident set size    :           66.57 MB (rank 0)
           Average resident set size :           66.57 MB
 Virtual:
       Per node:
           Peak memory consumption    :          467.97 MB (node sn109.localdomain,s.*)
           Average memory consumption :          467.97 MB
       Per rank:
           Peak memory consumption    :          467.97 MB (rank 0)
           Average memory consumption :          467.97 MB
```

and massif agrees with aps virtual memory consumption.

**Comment by jjellio** [comment]
I usually track resident memory.  It's not unusual to see large virtual allocations though. Linux will memory map alot of things the app may not use (depending on code path). Remember your binary (text) + shared library sizes will count against your apps memory use. (debug symbols aren't mapped into memory).  If you build statically (Trilinos can be built as static libraries via CMake with `-DBUILD_SHARED_LIBS=OFF`, and compile with C/CXX flags += `-ffunction-sections -fdata-sections` and link with  `-Wl,--gc-sections`. Doing that will give you a very small binary compared. I've seen resident memory usage go down by 20-40% depending on the app.  I wish we could use those flags daily, but they can break some of our introspection tools (like kokkos profiling).

You can also use Kokkos's profiler to see what memory is being allocated in Trilinos via Kokkos - given this is Epetra, I am not sure if it will help much.
(no need to rebuild)
clone `https://github.com/kokkos/kokkos-tools`; then head to `profiling/space-time-stack`. Build that file using something like `mpicc -fPIC -shared -O3`, get a shared library.

Then, before your run,
`export KOKKOS_PROFILING_LIBRARY=/path/to/kokkos-tools/space-time-profiler/library.so`

The app can slow down a little, but kokkos will dump all memory allocated by region at the end.

**Comment by jjellio** [comment]
To add, building trilinos static will only make Trilinos things static.  If you want to link OpenBLAS or MKL static, you'll need to change the libraries provided to CMake to make them static.

**Comment by david8dixon** [comment]
I am going to check in with intel to see what they think. I will update/close the issue once I've heard from them. Thanks!
