### ISSUE TITLE
TPetra:  Cannot access data on  host while a device view is alive

### ISSUE THREAD

**Issue by Chrismarsh** [trilinos/Trilinos#9519]
## Bug Report
@trilinos/tpetra 

### Description
I have code that works under Trilinos 12.x without issue. However, with 13.x master, I now get

```
terminate called after throwing an instance of 'std::runtime_error'
   what():  Tpetra::MultiVector: Cannot access data on  host while a device view is alive
```

when I call

```
typedef Tpetra::MultiVector<> MV;
RCP<MV> m_solution, m_rhs;
[...]
m_rhs->sumIntoGlobalValue(global_idx, 0, val);
```

Potentially useful stack trace snippet:
```
#9  0x00002aaab681f78e in Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::getLocalViewHost(Tpetra::Access::ReadWriteStruct) () from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/lib/libtpetra.so.13
#10 0x00002aaab682063f in Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::sumIntoLocalValue(int, unsigned long, double const&, bool) () from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/lib/libtpetra.so.13
#11 0x00002aaab6820c63 in Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::sumIntoGlobalValue(int, unsigned long, double const&, bool) () from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/lib/libtpetra.so.13
```

### Steps to Reproduce
1. SHA1:  master

**Comment by csiefer2** [comment]
Getting a host/device view when you have the other one outstanding is deprecated behavior.

If you really need to do this build with Tpetra deprecated code on. 

But that functionality is deprecated and will go away in the next major release.

**Comment by Chrismarsh** [comment]
Ah that is good to know. I think my confusion stems from running on MacOS continues to work as expected with 13.x/master whereas it does not on our linux HPC cluster. 
I'll build with deprecated now until I can get this working. To date I don't explicitly manage the device data, always assuming that "device" = host which petra can handle as the default case -- until now?

**Comment by csiefer2** [comment]
OpenMP build no Cuda?

**Comment by Chrismarsh** [comment]
MacOS = No OMP, No CUDA, MPI
Linux    =       OMP, No CUDA, MPI

**Comment by csiefer2** [comment]
Huh.  Well *that* shouldn't be happening.  Like master as of this week?  There was a bug along these lines that surfaced a month or two ago, but we thought we fixed that.

**Comment by Chrismarsh** [comment]
I rebuilt master @ 53ecba4c5e6b7b962967e5acdb6337d17b5002c7 and the problem persists.

Oddly, my smaller test case doesn't trigger the issue, but my larger test case does. 

Setting `OMP_NUM_THREADS=1 ./a.out` bypasses this problem

**Comment by Chrismarsh** [comment]
Trying to work around this as per

>If you really need to do this build with Tpetra deprecated code on.

`-DTpetra_ENABLE_DEPRECATED_CODE=ON`
does not resolve the problem either

**Comment by Chrismarsh** [comment]
Another note for you: same code works with release 13.0.1 so it seems to support that this is indeed a bug

**Comment by csiefer2** [comment]
Now we just need a reproducer.  Can you had us a cut-down version of your code?

**Comment by kevinrichardgreen** [comment]
Continuing from Chris.

So here's what I think the issue is: `Tpetra::MultiVector::sumIntoGlobalValue` (https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1MultiVector.html#abf793ee4674bffee54df32ecb94e8256) isn't respecting its 4th argument: `const bool 	atomic = useAtomicUpdatesByDefault`.

Basically, we construct our system in omp parallel regions like
```
#pragma omp parallel for
for ( ) {
  ...
  m_rhs->sumIntoGlobalValue(global_id,0,val,true);
   ...
}
```
From which we randomly/inconsistently trigger the exception in the initial report. Simply wrapping the sum into an omp critical section fixes the problem for us with Trilinos/master.

A couple of thoughts:
- Potentially something has changed with how the sum is implemented using views under the hood that breaks its thread safety.
- Are we mistaken in assuming that we could call this in a thread-safe manner, provided the atomic update is set to true?

**Comment by csiefer2** [comment]
Yeah, that's weird.

**Comment by kevinrichardgreen** [comment]
Yes I can try for a mwe.

I'm thinking it's inconsistent due to a race condition on views. I.e., one thread trying to "check out" a view before another one has returned its own (I can only speculate as to how host/device views get used under the hood)... and sometimes we just get super lucky and get through it.

Even though it's not tested for, is it intended to be thread-safe?

I see. It's not the most general use-case we have set up right now, but wwer really hoping that the atomic update would be sufficient here.

**Comment by csiefer2** [comment]
Yeah, there's no real reason why this code shouldn't be callable from OpenMP in a thread-safe manner.  From the function signature, it was clear it was intended to be that way at one point.

The host/device view checking was intended to be a way to prevent people from shooting themselves in the foot on systems with separate memory spaces (e.g. Cuda).  It was *supposed* to invisible to Serial  / OpenMP backends

**Comment by csiefer2** [comment]
I can get intermittent failures with a cut-down version of this test.  We'll discuss at our meeting today.

**Comment by csiefer2** [comment]
Turns out we fixed the problem for CrsMatrix, but missed MultiVector. 

 Once I get the PR up, I'll drop a link to that here for you to test.

**Comment by csiefer2** [comment]
@Chrismarsh As a warning, what you do in the example doesn't work in Debug mode, since sumIntoLocalValue's debug-time checks access RCP's in a way that isn't thread-safe.

We recommend you switch from raw OpenMP parallel for to Kokkos-based loops, since you're using capability we don't really test.  I *think* I finally got the PR right, and I'm waiting for the tests to confirm that.

**Comment by Chrismarsh** [comment]
@csiefer2 Good to know, thanks.

>We recommend you switch from raw OpenMP parallel for to Kokkos-based loops

Hmm ok. This is a big change for the code base, but we will look into what this entails.

**Comment by csiefer2** [comment]
> Hmm ok. This is a big change for the code base, but we will look into what this entails.

It is a big change, indeed.  But it is a necessary change for GPU portability, which is what most of our driving apps need.  Is that a place you want to go longer term?

**Comment by Chrismarsh** [comment]
Medium-term it is something we are interested in exploring and understanding how it improves our overall scalability. The past year+ has been going from a single process OMP program using ViennaCL to a hybrid OMP+MPI code using Trilinos. A lot of the effort has been around this change. Most of our nodes don't have GPU-compute available so it's not a huge current priority if that makes sense?

**Comment by csiefer2** [comment]
Makes perfect sense.  We have a number of other apps who also don't have access to GPU machines, and they're basically slow-walking GPU-ification for the same reason.  Out of curiousity, are you seeing any speedup using MPI+OpenMP vs. flat MPI everywhere?

**Comment by Chrismarsh** [comment]
>Out of curiousity, are you seeing any speedup using MPI+OpenMP vs. flat MPI everywhere?

My sense is yes, but I don't have up-to-date benchmarks to prove it!  The code I work on is an earth science code where there are lots of tight, trivially parallel loops over landscape elements -- these loops either do some computation (e.g., compute a temperature at an elevation) or insert into a trillinos matrix for a later solve. Historically these tight loops have benefited from omp, even when taking into account the thread spin up. However, I have not recently pitted the two modes against each other, so I am curious to see if this continues to hold!

**Comment by csiefer2** [comment]
If you do a comparison again and are allowed to share the results, I'd be interested in seeing them!

**Comment by csiefer2** [comment]
Code finally merged to develop.

**Comment by Chrismarsh** [comment]
Is this merged to trillinos develop?
