### ISSUE TITLE
Tempus: transient adjoint sensitivities not working correctly when 'Initial Time' is non-zero

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#9737]
Problem can be reproduced by setting ‘Initial Time: 0.1’ in Tempus_BDF2_SinCos_SA.xml in packages/tempus/test/BDF2, and then running ./Tempus_BDF2_ASA.exe.  The following error is encountered:

```
p=0: *** Caught standard std::exception of type 'std::logic_error' :

  /home/ikalash/transientAdjointSensitivities/Trilinos/packages/tempus/src/Tempus_SolutionHistory_impl.hpp:185:
  
  Throw number = 1
  
  Throw test that evaluated to true: !(minTime() <= time && time <= maxTime())
  
  Error - SolutionHistory::findState() Requested time out of range!
          [Min, Max] = [0, 0]
          time = 0.9
  
 [FAILED]  (8.719e-03 sec) BDF2_SinCos_ASA_UnitTest
Location: /home/ikalash/transientAdjointSensitivities/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2_ASA.cpp:46

```
@etphipp is aware of the problem and is looking at it.  I am opening the issue for documentation.

**Comment by etphipp** [comment]
@ikalash This should be resolved now.

**Comment by ikalash** [comment]
Thanks @etphipp .  yes I saw the PR get merged yesterday.  I am speaking in a conference this week and haven’t had a chance to try this out yet, but I will soon (either today or tomorrow).  Thanks!

**Comment by ikalash** [comment]
I just tested this in Piro and Albany and I'm still getting an error, but a different one:

```

p=0: *** Caught standard std::exception of type 'std::logic_error' :

 /nightlyAlbanyTests/Results/Trilinos/packages/tempus/src/Tempus_SolutionHistory_impl.hpp:185:
 
 Throw number = 1
 
 Throw test that evaluated to true: !(minTime() <= time && time <= maxTime())
 
 Error - SolutionHistory::findState() Requested time out of range!
         [Min, Max] = [0.0001, 0.01]
         time = 0.0001
```
Do you know what might be causing this behavior?  The Piro test case should be analogous to your SinCos test in Tempus.  You can find the input file here: https://github.com/trilinos/Trilinos/blob/master/packages/piro/test/_input_Tempus_BackwardEuler_SinCos.xml .  To reproduce the problem, just change "Initial Time" to something other than 0 and run the Piro_TempusSolver_SinCos_AdjointSensitivities_UnitTest (which will show up if you build Piro tests) .

**Comment by ikalash** [comment]
To clarify: it's the same error, just the ```[Min, Max]``` and time values printed are different - this is what I meant by the error being different.

**Comment by ikalash** [comment]
Also, I still see the issue when running the BDF2_SinCos_ASA_UnitTest in Tempus.  I'm using this sha of Trilinos, which should have your changes: 168bdafd58eb878369837a9c0ed61fb4bd5be74d .

**Comment by etphipp** [comment]
@ikalash Are you sure you have these changes?  I just updated to HEAD for the develop branch and changed the 'Initial Time' to 0.1 in the BDF2 SinCos ASA test and am not seeing this error.  The test fails when you make this change, but that is because the error in one of the checks is slightly different.

**Comment by ikalash** [comment]
Yes I'm sure it's up-to-date.  Try changing "Initial Iime" to 1e-4.  Then you should see the error.  I can confirm that if I set it to 0.1, the problem runs.

**Comment by ikalash** [comment]
It is because the code doesn't know to adapt the time-step to be able to hit the final time?  By setting "Initial Time" to 0.1, this problem is avoided.

**Comment by etphipp** [comment]
OK, there appear to be two things going wrong here.  The exception that is being thrown is because of this check failing in Tempus::SolutionHistory::findState() due to a small round-off error causing time < minTime():
```
  TEUCHOS_TEST_FOR_EXCEPTION(
    !(minTime() <= time && time <= maxTime()), std::logic_error,
    "Error - SolutionHistory::findState() Requested time out of range!\n"
    "        [Min, Max] = [" << minTime() << ", " << maxTime() << "]\n"
    "        time = "<< time <<"\n");
```
That is easy enough to fix by adding a small fudge-factor.  However, there is a more fundamental problem in how Tempus handles the final time as @ikalash alluded to.  It appears that if (t_final - t_initial) is not evenly divisible by the time-step size, Tempus does not adapt the final time step to hit the correct final time.  Since the final time is needed in the adjoint formulation, this messes up the resulting adjoint sensitivity calculation.  I can fix this by resetting the final time at the conclusion of the forward integration in the adjoint model.  

I will submit a PR for this shortly, but longer term, Tempus should consider adapting the final time step to hit the target final time as specified by the user, even in constant time-stepping cases.  @ccober6

**Comment by ikalash** [comment]
Thanks @etphipp !

**Comment by ccober6** [comment]
On the first issue of round-off error, yeah, I wondered if this was a problem.  I have been thinking about making use of some approximate equal, etc. functions to better handle this kind of case, especially after working on TimeEvents.

On the second issue of hitting the final time, initially Tempus's constant timestepping did exactly what you described above, i.e., constant timestep would be taken, adjusted "slightly" for numerical roundoff for output and adjust to hit the final time.  This was disliked by some apps, i.e., constant timestep should be constant timestep no matter what.

I can think of a couple ways we handle this situation: 1) I think we may be able to use the BasicVS that @ikalash implemented to take constant timesteps but hit the final time, or 2) we can develop a new TimeStepStrategy with the above attributes.

**Comment by etphipp** [comment]
What if you just had an option as to whether to adjust the step-size to hit t_final?

**Comment by rppawlo** [comment]
> What if you just had an option as to whether to adjust the step-size to hit t_final?

I thought the option to hit a final time point exactly already existed

**Comment by ccober6** [comment]
So TimeStepControlStrategy (TSCS) had two types: "Constant" and "Variable".  What currently differentiates them is "Constant" TSCS does not change the timestep ever, and "Variable" TSCS allows the timestep to change.  We do have "the option to hit the final time point exactly" in "Variable" TSCS because the timestep can be changed, but "Constant" TSCS does not because the timestep cannot be changed (similarly for adjusting the timestep to hit output times and any other TimeEvents that requires changing the timestep).

So we have a few options:
1. We can loosen this constraint (not changing the timestep) on the "Constant" TSCS and add an option to hit t_final.  We also might want to add options to allow adjusting the timestep for output and any other TimeEvents.
2. We can develop a new TSCS with the features we would like, and leave the current TimeStepControlStratgeyConstant unchanged.
3. We can possibly use BasicVS (which is a "Variable" TSCS), and set its parameters to so that it is constant timestep but would hit t_final and other TimeEvents.

I am open to what is easiest for the user to understand and use.  I think that either option 1 or 2 is better.  Option 3 requires users to have knowledge of BasicVS and it could have some complexities (but is an option if you are a user and need a quick solution).  What option do you'all think is better?

**Comment by etphipp** [comment]
I would suggest option 1.  I would think users would expect even constant time stepping to adjust the time-step to hit t_final.

**Comment by ccober6** [comment]
I tend to agree.  

I think the way we would want to handle output and TimeEvents for this, would be to take two partial time steps (one to go from the constant timestep to the output time, and a second to go from the output time back to the constant timestep interval).  That way after the output the simulation is back on the constant timestep interval.  Thoughts?

**Comment by etphipp** [comment]
For intermediate time events, or even the final time, can you not just interpolate?

**Comment by ccober6** [comment]
Yeah, we could that also, so long as the user is comfortable with that (e.g., using the output for just viz).  The one exception, I can think of, would be for restarts.  Interpolated solutions might not satisfy some constraints, like mass/energy conservation.  So restarts might have trouble getting started, and would not likely match runs where restart was not used.

**Comment by ccober6** [comment]
The other case were I do not think interpolation would work is when the SolutionHistory is limited to one SolutionState.  @etphipp, do you recall if the interpolation handles this case?

**Comment by etphipp** [comment]
I do not recall.

**Comment by ikalash** [comment]
Thanks @etphipp for the second fix.  Things work better now.  I did notice that for certain initial times in Albany I get now a new error: 

```
p=0: *** Caught standard std::exception of type 'std::logic_error' :

 /nightlyAlbanyTests/Results/Trilinos/packages/tempus/src/Tempus_SolutionHistory_impl.hpp:208:

 Throw number = 1

 Throw test that evaluated to true: state_it == history_->end()

 Error - SolutionHistory::findState()!
         Did not find a SolutionState with time = 0.0099

```
I am not sure how likely this case is to come up in practice, so if you wanted to leave things as is until you figure out some of the things in the discussion above, I'm OK with this.
