### ISSUE TITLE
Tempus?: FPEs/slowdown in Albany tests using Tempus

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#9767]
Several of our nightly tests in Albany and Albany/LCM are failing due to FPEs, I believe due to changes in Tempus.  Here is an example of the output: 

```
STKDiscretization::writeSolution: writing time 0.00000000000000000e+00 to index 1 in file ./thermal-vardt.e-s.0
Time = 0.00000000000000000e+00
         Response[0] = 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.63076923e+02  
      1 *  (dt = 1.000e+99, new = 7.200e+03)  Resetting constant dt.
[algol:2735787:0:2735787] Caught signal 8 (Floating point exception: floating-point invalid operation)
[algol:2735783:0:2735783] Caught signal 8 (Floating point exception: floating-point invalid operation)
[algol:2735786:0:2735786] Caught signal 8 (Floating point exception: floating-point invalid operation)
[algol:2735788:0:2735788] Caught signal 8 (Floating point exception: floating-point invalid operation)
==== backtrace (tid:2735783) ====
 0  /usr/lib64/libucs.so.0(ucs_handle_error+0x2a4) [0x7febac19d5c4]
 1  /usr/lib64/libucs.so.0(+0x2a47d) [0x7febac1a047d]
 2  /usr/lib64/libucs.so.0(+0x2a75a) [0x7febac1a075a]
```
This line in particular looks suspicious to me: ``` 1 *  (dt = 1.000e+99, new = 7.200e+03)  Resetting constant dt.```  It was not present in yesterday's tests (https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1566823&build=23270) which have instead the following printed to screen: ```   1 *  (dt = 1.000e+00, new = 7.200e+03)  Resetting constant dt.```.  I noticed we additionally have some new tests timing out in Albany, e.g., https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1571429&build=23302 - while this could be a fluke, I suspect it may be related to this issue.

@trilinos/tempus 

Tagging @lxmota who is likely interested in this issue too.

**Comment by ccober6** [comment]
Hi @ikalash, so the 1.0e+99 is the default initial timestep and it was changed from 1.0 to 1.0e+99.  The default initial time is 0.0 and the default final time is 1.0e+99.  Previously with the default initial timestep set to 1.0 means you have 1e+99 timesteps by default, which caused some numerical problems.  With the initial default timestep set to 1.0e+99 means you have 1 timestep by default.

Your output indicates that you are using the initial default timestep in your setup.  The quick fix would be to specify your initial timestep explicitly (e.g., currentState->setTimeStep(dt);) during your initialization.  

A more permanent fix would be to have the default final time be 1.0, which makes the default initial timestep 1.0 again.  I went with 1.0+99 because it would be clear where it came from, where 1.0 is a little less clear.  But may be it is not that important.

**Comment by ccober6** [comment]
As far as the slowdowns, I can not think of anything that might cause it from the Tempus side.  I will test develop on my Mac since that is what I am most familiar with as for as runtimes, and see what they look like.

**Comment by ccober6** [comment]
So I have done some clean builds before and after recent Tempus changes, and I get consistent times.  So I cannot point to anything on the Tempus side that might cause a slowdown.

**Comment by ikalash** [comment]
Thanks for checking about the slowdowns @ccober6 and sorry for not replying earlier - was in an all day workshop today.  

The reason I think the slowdown is due to Tempus is b/c the output printed to screen having to do w/ dt changed.  The output now looks like this:
```
1     1.000e+01  1.000e+01  0.000e+00  0.000e+00  1.0    0      2.864e-01  
STKDiscretization::writeSolution: writing time 1.000e+01 to index 2 in file thermal1D_out.exo
Time = 1.000e+01
         Response[0] = 2.50131170e+02  
     2 *  (dt = 1.000e+01, new = 1.000e+03)  Reset dt after time event.
     2 *  (dt = 1.000e+03, new = 1.000e+01)  Adjusting dt to hit the next TimeEvent.
2     2.000e+01  1.000e+01  0.000e+00  0.000e+00  1.0    0      2.130e-01  
STKDiscretization::writeSolution: writing time 2.000e+01 to index 3 in file thermal1D_out.exo
Time = 2.000e+01
         Response[0] = 2.50136798e+02  
     3 *  (dt = 1.000e+01, new = 1.000e+03)  Reset dt after time event.
     3 *  (dt = 1.000e+03, new = 1.000e+01)  Adjusting dt to hit the next TimeEvent.
3     3.000e+01  1.000e+01  0.000e+00  0.000e+00  1.0    0      2.129e-01  
```
(https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1571429&build=23302) 

Here is how it looks like before for the same test case:
```
1     1.000e+03  1.000e+03  0.000e+00  0.000e+00  1.0    0      2.905e-01  
STKDiscretization::writeSolution: writing time 1.000e+03 to index 2 in file thermal1D_out.exo
Time = 1.000e+03
         Response[0] = 2.50689137e+02  
STKDiscretization::writeSolution: writing time 2.00000000e+03 to index 3 in file thermal1D_out.exo
Time = 2.00000000e+03
         Response[0] = 2.51253884e+02  
```
(https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1567747&build=23249)

I'm guessing all the I/O is slowing down the test substantially.

**Comment by ccober6** [comment]
So I am reading this correctly that your dt changed from 1000.0 to 10.0, therefore you have 100x more output times?

**Comment by ikalash** [comment]
@ccober6 : yes, it looks like it.

**Comment by ccober6** [comment]
Hmm... Can you post the Tempus parameterList?

**Comment by ikalash** [comment]
> Hi @ikalash, so the 1.0e+99 is the default initial timestep and it was changed from 1.0 to 1.0e+99. The default initial time is 0.0 and the default final time is 1.0e+99. Previously with the default initial timestep set to 1.0 means you have 1e+99 timesteps by default, which caused some numerical problems. With the initial default timestep set to 1.0e+99 means you have 1 timestep by default.
> 
> Your output indicates that you are using the initial default timestep in your setup. The quick fix would be to specify your initial timestep explicitly (e.g., currentState->setTimeStep(dt);) during your initialization.
> 
> A more permanent fix would be to have the default final time be 1.0, which makes the default initial timestep 1.0 again. I went with 1.0+99 because it would be clear where it came from, where 1.0 is a little less clear. But may be it is not that important.

Thanks for the tip.  We are setting the initial time-step as follows in these runs: https://github.com/trilinos/Trilinos/blob/master/packages/piro/src/Piro_TempusSolver_Def.hpp#L585-L587 .  Why is this not enough?

**Comment by ikalash** [comment]
> Hmm... Can you post the Tempus parameterList?

Here is the input file for the Thermal1D problem whose output you were looking at: https://github.com/sandialabs/Albany/blob/master/tests/small/Thermal1D/input.yaml .

**Comment by sconde** [comment]
Question: apart from it being slow, is the solution correct?

**Comment by ikalash** [comment]
@sconde : yes, it looks to be correct.  In the nightlies where the test does not timeout (e.g., non-debug builds), it passes.

**Comment by ccober6** [comment]
> > Hi @ikalash, so the 1.0e+99 is the default initial timestep and it was changed from 1.0 to 1.0e+99. The default initial time is 0.0 and the default final time is 1.0e+99. Previously with the default initial timestep set to 1.0 means you have 1e+99 timesteps by default, which caused some numerical problems. With the initial default timestep set to 1.0e+99 means you have 1 timestep by default.
> > Your output indicates that you are using the initial default timestep in your setup. The quick fix would be to specify your initial timestep explicitly (e.g., currentState->setTimeStep(dt);) during your initialization.
> > A more permanent fix would be to have the default final time be 1.0, which makes the default initial timestep 1.0 again. I went with 1.0+99 because it would be clear where it came from, where 1.0 is a little less clear. But may be it is not that important.
> 
> Thanks for the tip. We are setting the initial time-step as follows in these runs: https://github.com/trilinos/Trilinos/blob/master/packages/piro/src/Piro_TempusSolver_Def.hpp#L585-L587 . Why is this not enough?

So the short answer is these lines are setting the initial timestep on the TimeStepControl, and not on the SolutionState (e.g., currentState).  

TimeStepControl does not own any SolutionState, and only has one function that accesses the SolutionState through the SolutionHistory(i.e., setNextTimeStep()).

So during the construction/initialization of the SolutionState (i.e., setting the initial conditions), one can set the initial timestep, e.g., IntegratorBasic::initializeSolutionHistory() in Tempus_IntegratorBasic_imp.hpp:125 `state->setTimeStep(timeStepControl_->getInitTimeStep());`

If you are using IntegratorBasic and calling initialSolutionHistory(), this probably means, initialSolutionHistory() is being called before Piro::TempusSolver::setInitTimeStep().

Does this make sense?  Let me know if you have any questions.

**Comment by ccober6** [comment]
On the slowdown question: 

Yes, I believe it is due to too many output times (dt changed from 1000.0 to 10.0, therefore have 100x more output times).  If the yaml input has not changed (which I believe is the case), then I think **the behavior before** the recent Tempus changes was incorrect!  :(  But it is **working now** as expected.  :)

Given the yaml input (from https://github.com/sandialabs/Albany/blob/master/tests/small/Thermal1D/input.yaml) 
```
  Time Step Control:
     Initial Time Step: 1.0e+03
     Output Time Interval: 1.00000000000000000e+01
     Output Index Interval: 1000
```
The initial timestep should be 1000.0 but because of the output time interval is 10.0, TimeStepControl is selecting 10.0 for the timestep to hit the output time.  So I think you want to set `Output Time Interval: 1.0e+03` to get the previous behavior.  Since this is every time step, you could also get it by removing the `Output Time Interval:` line and changing the output index interval to `Output Index Interval: 1`.

**Comment by ikalash** [comment]
@ccober6 : first about the FPEs.  You're right that for the test for which I pasted the output, initialSolutionHistory() was being called before Piro::TempusSolver::setInitTimeStep().  I'll take a look at that.  We have other tests that fail due to issues in Tempus_TimeEventRange_impl.hpp, it looks like (and this would happen if the initialSolutionHistory() and setInitialTimeStep() ordering were fixed):
```
(gdb) bt
#0  Tempus::TimeEventRange<double>::eventInRange (this=0x952d80, time1=0, time2=0.050000000000000003)
    at /home/ikalash/ACE/Trilinos/packages/tempus/src/Tempus_TimeEventRange_impl.hpp:261
#1  0x00007fffefdf6398 in Tempus::TimeEventComposite<double>::eventInRange (this=0x962d70, time1=0, time2=0.050000000000000003, 
    timeEvents=std::vector of length 0, capacity 0) at /home/ikalash/ACE/Trilinos/packages/tempus/src/Tempus_TimeEventComposite.hpp:235
#2  0x00007fffefde8a90 in Tempus::TimeStepControl<double>::setNextTimeStep (this=0x953a90, solutionHistory=..., integratorStatus=@0x934878: Tempus::WORKING)
    at /home/ikalash/ACE/Trilinos/packages/tempus/src/Tempus_TimeStepControl_impl.hpp:310
#3  0x00007fffefbf329e in Tempus::IntegratorBasicOld<double>::advanceTime (this=0x934790)
    at /home/ikalash/ACE/Trilinos/packages/tempus/src/Tempus_IntegratorBasicOld_impl.hpp:401
#4  0x00007fffefbf3739 in Tempus::IntegratorBasicOld<double>::advanceTime (this=0x934790, timeFinal=0.050000000000000003)
    at /home/ikalash/ACE/Trilinos/packages/tempus/src/Tempus_IntegratorBasicOld_impl.hpp:349
#5  0x00007ffff6ba9bf4 in Piro::TempusIntegrator<double>::advanceTime (this=0x8f6330, time_final=0.050000000000000003)
    at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Piro_TempusIntegrator_Def.hpp:132
#6  0x00007ffff6b9723c in Piro::TempusSolver<double>::evalModelImpl (this=0x8bfa40, inArgs=..., outArgs=...)
    at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Piro_TempusSolver_Def.hpp:515
#7  0x00007ffff6b8cd2b in Thyra::ModelEvaluatorDefaultBase<double>::evalModel (this=0x8bfc18, inArgs=..., outArgs=...)
    at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Thyra_ModelEvaluatorDefaultBase.hpp:709
#8  0x00007ffff2c5fe66 in LCM::SchwarzAlternating::SchwarzLoopDynamics (this=0x734c50)
    at /home/ikalash/ACE/Albany-LCM-master/src/LCM/solvers/Schwarz_Alternating.cpp:617
#9  0x00007ffff2c5e339 in LCM::SchwarzAlternating::evalModelImpl (this=0x734c50)
    at /home/ikalash/ACE/Albany-LCM-master/src/LCM/solvers/Schwarz_Alternating.cpp:403
#10 0x00007ffff6b8cd2b in Thyra::ModelEvaluatorDefaultBase<double>::evalModel (this=0x734f40, inArgs=..., outArgs=...)
    at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Thyra_ModelEvaluatorDefaultBase.hpp:709
#11 0x00000000004827e7 in Piro::Detail::PerformSolveImpl<double, Thyra::VectorBase<double> const, Thyra::MultiVectorBase<double> const> (model=..., 
    computeResponses=..., computeSensitivities=false, responses=..., sensitivities=..., directions=..., reducedHessian=..., observer=...)
    at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Piro_PerformSolve_Def.hpp:140
#12 0x000000000047dea0 in Piro::Detail::PerformSolveImpl<double, Thyra::VectorBase<double> const, Thyra::MultiVectorBase<double> const> (model=..., 
    solveParams=..., responses=..., sensitivities=...) at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Piro_PerformSolve_Def.hpp:186
#13 0x000000000047ad62 in Piro::PerformSolveBase<double> (piroModel=..., solveParams=..., responses=..., sensitivities=...)
    at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Piro_PerformSolve_Def.hpp:379
#14 0x0000000000476d34 in Piro::PerformSolve<double> (piroModel=..., solveParams=..., responses=..., sensitivities=...)
    at /home/ikalash/ACE/Trilinos/build-dbg/install/include/Piro_PerformSolve_Def.hpp:294
#15 0x0000000000466fb5 in main (argc=2, argv=0x7fffffffd058) at /home/ikalash/ACE/Albany-LCM-master/src/Main_Solve.cpp:111
```
I went and printed various quantities before this line https://github.com/trilinos/Trilinos/blob/develop/packages/tempus/src/Tempus_TimeEventRange_impl.hpp#L258-L259 and am getting:
```
IKT time1, start_, absTol_ stride_ = 0, 0, 2.22045e-14, 0
```
If ```stride_ is 0```, you're diving by 0.  Are the parens messed up maybe and you intended to divide by ```(stride_ - 0.5)```?

**Comment by ikalash** [comment]
@ccober6 : regarding the slowdown.  Oh ok I see!  I never paid attention to the 'Output Time Interval' value (I guess b/c it was not correct), so it did not occur to me to look at that.  (You are right that no changes to the Albany input files have been made).  I'll modify the input files - we don't need the output index set the way it is for these tests.

**Comment by ccober6** [comment]
> @ccober6 : first about the FPEs. You're right that for the test for which I pasted the output, initialSolutionHistory() was being called before Piro::TempusSolver::setInitTimeStep(). I'll take a look at that. We have other tests that fail due to issues in Tempus_TimeEventRange_impl.hpp, it looks like (and this would happen if the initialSolutionHistory() and setInitialTimeStep() ordering were fixed):
> 
> 
> I went and printed various quantities before this line https://github.com/trilinos/Trilinos/blob/develop/packages/tempus/src/Tempus_TimeEventRange_impl.hpp#L258-L259 and am getting:
> 
> ```
> IKT time1, start_, absTol_ stride_ = 0, 0, 2.22045e-14, 0
> ```
> 
> If `stride_ is 0`, you're diving by 0. Are the parens messed up maybe and you intended to divide by `(stride_ - 0.5)`?

Hmm... let me take a look.  I think the parens are ok.  Can you post the output from 

```
  Teuchos::RCP<Teuchos::FancyOStream> my_out =
    Teuchos::fancyOStream(Teuchos::rcpFromRef(std::cout));
  this->describe(*my_out, Teuchos::VERB_EXTREME);
```

placed around Tempus_TimeEventRange_impl.hpp#L253?

**Comment by ikalash** [comment]
@ccober6 : absolutely.  Here is the output: 

```
Tempus - IntegratorBasic
Fri Oct  1 20:30:46 2021

  Stepper = Newmark Implicit d-Form
  Simulation Time Range  [0.00000000000000000e+00, 5.00000000000000028e-02]
  Simulation Index Range [0, 1000000]
============================================================================
  Step       Time         dt  Abs Error  Rel Error  Order  nFail  dCompTime
  TimeEventRange:
    name            = Output Time Interval
    Type            = Range
    start_          = 0
    stop_           = 0
    stride_         = 0
    numEvents_      = 1
    timeScale_      = 1
    relTol_         = 2.22045e-14
    absTol_         = 2.22045e-14
    landOnExactly_  = 1
```

**Comment by ccober6** [comment]
@ikalash Ok, this has forced me to start looking at testing with FPEs.  :)

**Comment by ikalash** [comment]
@ccober6 : will you fix the problem?

**Comment by ccober6** [comment]
@ikalash Absolutely!  I already have a fix for this particular failure, but I am working on more general fix and testing.  Is this holding you up, as I may need a few days to get the final solution ready?

**Comment by ikalash** [comment]
I believe this is fixed, but this PR did not make it into the nightlies last night, so I wasn't able to verify there across all platforms.  I'll close this issue tomorrow if the nightlies are clean.

**Comment by ccober6** [comment]
Hmm...  I think it will still fail the FPE (divide by zero).
